import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as THREE from 'three';
import {Viewer} from '../ui/viewer.js';
import {runStereographicWorkerJob,stereographicWorkerTransferables} from '../ui/stereographic-worker-geometry.mjs';
import {resolveExplosion,explosionGeometry} from '../ui/explosion.mjs';
const cases=JSON.parse(await readFile(new URL('./fixtures/element-content-native-cases.json',import.meta.url),'utf8')),tick=()=>new Promise(resolve=>setImmediate(resolve));
const makeCanvas=()=>({width:0,height:0,getContext:()=>({clearRect(){},drawImage(){},save(){},restore(){},translate(){},rotate(){},measureText(t){return {width:t.length*7};},fillText(){}})}),options={makeCanvas,decodeImage:async()=>({width:2,height:2,close(){}})};
class HeldWorker{constructor(){this.jobs=[];this.listeners=new Map();}addEventListener(t,fn){this.listeners.set(t,fn);}removeEventListener(t){this.listeners.delete(t);}postMessage(job,buffers){this.jobs.push(structuredClone(job,{transfer:buffers}));}reply(){const job=this.jobs.shift(),result=runStereographicWorkerJob(job);assert.equal(result.type,'geometry-result',result.message);this.listeners.get('message')?.({data:structuredClone(result,{transfer:stereographicWorkerTransferables(result)})});}terminate(){}}
function viewer(model,worker=false){const v=Object.create(Viewer.prototype);v.group=new THREE.Group();v.setModel(model);v.cameraProjection='orthographic';v.orthographicHalfHeight=2;v.camera=new THREE.OrthographicCamera(-2,2,2,-2,.01,1000);v.orthographicCamera=v.camera;v.perspectiveCamera=new THREE.PerspectiveCamera(38,1,.01,1000);v.camera.position.set(0,0,6);v.camera.lookAt(0,0,0);v.camera.updateMatrixWorld();v.controls={target:new THREE.Vector3(),update(){}};v.renderer={domElement:{getBoundingClientRect:()=>({width:900,height:900})},render(){}};v.worker=worker?new HeldWorker():null;v.stereographicWorkerFactory=()=>v.worker;v.stereographicWorkerClock={now:()=>0,setTimer:()=>1,clearTimer(){}};return v;}
async function drain(v){for(let i=0;i<12;i++){if(v.worker.jobs.length)v.worker.reply();await tick();if(!v.worker.jobs.length&&!v.stereographicWorker.transport.pending.active)return;}assert.fail('Worker must drain bounded jobs.');}
function mesh(v){return v.elementContentLayer.group.children.find(o=>o.isMesh);}
test('actual 4D synchronous S3 and custom perspective reuse emitted patches with bounded source UV',async()=>{const f=structuredClone(cases.fourD),before=JSON.stringify(f.source),v=viewer(f.source);try{v.setDisplay({projection:'stereographic',faces:true,angles:[9,7,4,3,2,1],surfaceColors:'source'});await v.setElementContent(f.descriptor,options);assert.equal(v.elementContentDiagnostic,null);const overlay=mesh(v),packed=v.stereographicGeometry.packed,expected=[];for(let i=0;i<packed.faceIds.length;i++)if(packed.faceIds[i]===0)expected.push(...packed.triangles.subarray(i*9,i*9+9));assert.deepEqual(Array.from(overlay.geometry.attributes.position.array),expected);for(const n of overlay.geometry.attributes.uv.array)assert.ok(n>=-3e-5&&n<=1+3e-5);assert.ok((await v.prepareCapture()).elementContent.ready);v.setDisplay({projection:'perspective',perspectiveDistance4D:2,perspectiveNear4D:.08,angles:[9,7,4,3,2,1],faces:true});assert.equal(v.elementContentDiagnostic,null);assert.ok(mesh(v).geometry.attributes.position.count>0);assert.equal(JSON.stringify(f.source),before);}finally{v.clear();}});
test('pending desired rotation/shrink cannot mix old surface pose with new UV recipe',async()=>{const f=structuredClone(cases.fourD),v=viewer(f.source,true);try{v.setDisplay({projection:'stereographic',angles:[9,7,4,3,2,1],faces:true,cellShrink:.8});await drain(v);await v.setElementContent(f.descriptor,options);const oldPositions=Array.from(mesh(v).geometry.attributes.position.array),oldUV=Array.from(mesh(v).geometry.attributes.uv.array),published=v.publishedPickState;v.setDisplay({projection:'stereographic',angles:[30,13,8,16,7,3],faces:true,cellShrink:.6});assert.strictEqual(v.publishedPickState,published);v.elementContentLayer.rebuild();assert.deepEqual(Array.from(mesh(v).geometry.attributes.position.array),oldPositions);assert.deepEqual(Array.from(mesh(v).geometry.attributes.uv.array),oldUV);assert.equal(v.elementContentDiagnostic,null);await drain(v);assert.notDeepEqual(Array.from(mesh(v).geometry.attributes.position.array),oldPositions);assert.equal(v.elementContentDiagnostic,null);assert.equal(v.elementContentLayer.displayReceipt.positions,v.surfaceGeometry.attributes.position.array);}finally{v.clear();}});
test('owner-bound face shrink, manual cell isolation and full-size geometry restoration retain content mapping',async()=>{const f=structuredClone(cases.fourD),v=viewer(f.source);try{const owner=f.source.cells.findIndex(row=>row.includes(0));v.setDisplay({projection:'perspective',faces:true,cellShrink:.6,isolatedCell:owner,angles:[7,4,3,2,1,0]});await v.setElementContent(f.descriptor,options);assert.equal(v.elementContentDiagnostic,null);assert.ok(mesh(v));v.setDisplay({projection:'perspective',faces:true,hiddenCells:[owner],cellShrink:.6});assert.equal(v.elementContentDiagnostic,null);assert.ok(mesh(v),'Other shared source-face owner remains visible.');v.setDisplay({projection:'perspective',faces:false});assert.equal(mesh(v),undefined);assert.ok((await v.prepareCapture()).elementContent.ready);v.setDisplay({projection:'perspective',faces:true,cellShrink:1});assert.ok(mesh(v));}finally{v.clear();}});
test('native folded net face correspondence carries PNG/text without inventing source indices',async()=>{const f=structuredClone(cases.net),v=viewer(f.source),before=JSON.stringify(f.source);try{v.setNet(f.net);await v.setElementContent(f.descriptor,{...options,sourceModel:f.source});assert.equal(v.elementContentDiagnostic,null);assert.ok(mesh(v));const uv=Array.from(mesh(v).geometry.attributes.uv.array),positions=Array.from(mesh(v).geometry.attributes.position.array);v.setFold(.6);assert.equal(v.elementContentDiagnostic,null);const after=mesh(v);assert.notDeepEqual(Array.from(after.geometry.attributes.position.array),positions);const newUV=Array.from(after.geometry.attributes.uv.array);uv.forEach((x,i)=>assert.ok(Math.abs(x-newUV[i])<1e-6));assert.ok((await v.prepareCapture()).elementContent.ready);assert.equal(JSON.stringify(f.source),before);}finally{v.clear();}});
test('unverified net source cycles and unrelated dual source refuse content capture explicitly',async()=>{const f=structuredClone(cases.net),v=viewer(f.source);try{v.setNet(f.net);v.net.faces.find(face=>face.id===0).sourceVertices.reverse();const result=await v.setElementContent(f.descriptor,{...options,sourceModel:f.source});assert.match(result.diagnostic,/cycle/);await assert.rejects(v.prepareCapture(),/content/);v.setModel({...f.source,id:'unrelated-derived'});await assert.rejects(v.setElementContent(f.descriptor,{...options,sourceModel:f.source}),/correspondence/);}finally{v.clear();}});
test('source face explosion translates content with its exact rendered face instance and source RGBA',async()=>{const f=structuredClone(cases.net),v=viewer(f.source);try{const resolved=resolveExplosion(f.source,{direction:'radial'});assert.equal(resolved.supported,true);const explosion=explosionGeometry(resolved,.4);assert.equal(v.setExplosion(explosion).supported,true);v.setDisplay({projection:'orthographic',faces:true,angles:[9,3,4,0,0,0]});await v.setElementContent(f.descriptor,options);assert.equal(v.elementContentDiagnostic,null);assert.ok(mesh(v));assert.ok((await v.prepareCapture()).elementContent.ready);}finally{v.clear();}});
