import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as THREE from 'three';
import {portableContentSource,pythonFloatHex,verifyContentDescriptor,sha256Content} from '../ui/element-content-source.mjs';
import {validateContentFaceFrame,contentPresentationFrame,recoverContentXY,contentUV} from '../ui/element-content-mapping.mjs';
import {compileContentCanvas,decodeContentPNG} from '../ui/element-content-canvas.mjs';
import {Viewer} from '../ui/viewer.js';
import {project} from '../ui/projection.js';
const fixture=JSON.parse(await readFile(new URL('./fixtures/element-content-native-fixture.json',import.meta.url),'utf8')),copy=()=>structuredClone(fixture),sub=(a,b)=>a.map((x,i)=>x-b[i]);
function makeCanvas(){const calls=[],ctx={clearRect(...args){calls.push(['clear',...args]);},drawImage(...args){calls.push(['image',...args]);},save(){},restore(){},translate(...args){calls.push(['translate',...args]);},rotate(...args){calls.push(['rotate',...args]);},measureText(t){return {width:t.length*7};},fillText(...args){calls.push(['text',...args,this.font,this.fillStyle]);}};return {width:0,height:0,calls,getContext:()=>ctx};}
const image=()=>({width:2,height:2,closed:false,close(){this.closed=true;}}),options={makeCanvas,decodeImage:async()=>image()};
function viewer(model){const v=Object.create(Viewer.prototype);v.group=new THREE.Group();v.setModel(model);v.stereographicWorkerFactory=()=>null;return v;}
const close=(a,b,eps=3e-6)=>a.forEach((x,i)=>assert.ok(Math.abs(x-b[i])<eps,`${a} != ${b}`));
test('actual native portable descriptor agrees byte-for-byte including astral ordering and binary64 spellings',async()=>{assert.equal(portableContentSource(fixture.source),fixture.portable);assert.equal(pythonFloatHex(-0),'0x0.0p+0');assert.equal(pythonFloatHex(2),'0x1.0000000000000p+1');assert.equal(pythonFloatHex(5e-324),'0x0.0000000000001p-1022');assert.equal(await sha256Content(fixture.portable),fixture.descriptor.sourceSha256);await verifyContentDescriptor(fixture.source,fixture.descriptor);});
test('full attributes/source ID and descriptor fingerprint changes refuse instead of geometrical-ID shortcuts',async()=>{for(const mutate of [f=>f.source.metadata.coordinateUnits='cm',f=>f.source.metadata.offColors.faces[0].values[3]=146,f=>f.source.metadata.notes.integral=3,f=>f.source.id+='changed',f=>f.descriptor.sourceFingerprint='f'.repeat(64)]){const f=copy();mutate(f);await assert.rejects(verifyContentDescriptor(f.source,f.descriptor),/mismatch/);}const c=new AbortController();c.abort();await assert.rejects(verifyContentDescriptor(fixture.source,fixture.descriptor,{signal:c.signal}),{name:'AbortError'});});
test('native ordered face frame reconstructs every source corner and refuses fabricated UV',()=>{const entry=fixture.descriptor.entries[0],f=validateContentFaceFrame(fixture.source,entry);f.xy.forEach((p,i)=>close(f.origin.map((x,k)=>x+f.u[k]*p[0]+f.v[k]*p[1]),fixture.source.vertices[entry.sourceVertexIds[i]],1e-10));const forged=structuredClone(entry);forged.faceFrame.xy[2][1]+=.1;assert.throws(()=>validateContentFaceFrame(fixture.source,forged),/reconstruct/);});
test('source-frame UV agrees under ordinary pose, scale, and independently translated/shrunken instance',()=>{const f=validateContentFaceFrame(fixture.source,fixture.descriptor.entries[0]),frame=contentPresentationFrame(f,{center:[0,0,0],radius:3,angles:[21,9,6,0,0,0],translation:[.4,-.2,.3]}),xy=[.25,.55],point=frame.origin.map((x,k)=>x+frame.u[k]*xy[0]+frame.v[k]*xy[1]),result=recoverContentXY(point,frame);assert.equal(result.supported,true);close(result.xy,xy);close(contentUV(result.xy,frame),xy.map((x,k)=>(x-f.low[k])/(f.high[k]-f.low[k])));});
test('stereo inverse ray solves all 4D source-plane constraints after pose exactly once',()=>{const f={origin:[-.4,-.3,.5,-.6],u:[1,0,0,0],v:[0,1,0,0],low:[0,0],high:[1,1]},matrix=[[0,-1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]],frame=contentPresentationFrame(f,{center:[0,0,0,0],radius:2,matrix,angles:[21,9,0,7,12,19],translation:[.2,.1,0,-.1],shrink:.6,cellCenter:[.1,.2,.3,-.2]}),xy=[.31,.27],raw=frame.origin.map((x,k)=>x+frame.u[k]*xy[0]+frame.v[k]*xy[1]),p=project(raw,'stereographic');assert.equal(p.clipped,false);const result=recoverContentXY(p.point,frame,{projection:'stereographic'});assert.equal(result.supported,true);close(result.xy,xy,1e-9);assert.ok(result.rayScale>0);const wrong={...frame,origin:frame.origin.map((x,k)=>x+(k===2?.2:0))};assert.equal(recoverContentXY(p.point,wrong,{projection:'stereographic'}).supported,false);});
test('perspective inverse mapping uses actual adjustable 4D eye and rejects wrong constraints',()=>{const frame={origin:[.1,.2,.5,-.3],u:[1,0,0,0],v:[0,1,0,0],low:[0,0],high:[1,1]},xy=[.2,.4],raw=frame.origin.map((x,k)=>x+frame.u[k]*xy[0]+frame.v[k]*xy[1]),p=project(raw,'perspective',{distance:2,near:.08}),r=recoverContentXY(p.point,frame,{projection:'perspective',distance:2});assert.equal(r.supported,true);close(r.xy,xy);assert.equal(recoverContentXY(p.point,{...frame,origin:[.1,.2,.8,-.3]},{projection:'perspective',distance:2}).supported,false);});
test('pole, origin-containing affine face, and collapsed parallel frames have explicit refusal',()=>{const frame={origin:[0,0,0,0],u:[1,0,0,0],v:[0,1,0,0],low:[0,0],high:[1,1]};assert.equal(recoverContentXY([1,0,0],frame,{projection:'stereographic'}).supported,false);assert.equal(recoverContentXY([20,0,0],{...frame,origin:[0,0,0,1]},{projection:'stereographic'}).supported,false);assert.equal(recoverContentXY([0,0,0],{...frame,u:[0,0,0,1],v:[0,1,0,0]}).supported,false);});
test('local canvas compiles native formatted runs, mm scale, sub/superscripts, no markup HTML',()=>{const f=fixture.descriptor.entries[0],frame=validateContentFaceFrame(fixture.source,f),drawing=compileContentCanvas(f,frame,{firstEdgeLength:2,referenceEdgeLengthMm:25,makeCanvas,image:image()}),calls=drawing.canvas.calls;assert.equal(drawing.mmPerUnit,12.5);assert.ok(calls.some(c=>c[0]==='text'&&c[1]==='A & B'));assert.ok(calls.some(c=>c[0]==='text'&&c[1]==='2'));assert.ok(calls.every(c=>typeof c[1]!=='string'||!c[1].includes('<b>')));assert.ok(drawing.pixels<=4*1024*1024);const forged=structuredClone(f);forged.runs[0].style.font='url(https://example.com/font)';assert.throws(()=>compileContentCanvas(forged,frame,{firstEdgeLength:2,referenceEdgeLengthMm:25,makeCanvas}),/Unverified/);});
test('normalized PNG signature/dimensions/hash are verified before local decoding',async()=>{const [key,asset]=Object.entries(fixture.descriptor.assets)[0],decoded=await decodeContentPNG(asset,key,{decode:async()=>image()});assert.equal(decoded.width,2);const forged=structuredClone(asset);forged.width=3;await assert.rejects(decodeContentPNG(forged,key,{decode:async()=>image()}),/header/);await assert.rejects(decodeContentPNG(asset,'f'.repeat(64),{decode:async()=>image()}),/hash/);});
test('actual copied Viewer overlays exactly its own qualified surface triangles with matching alpha and source owner',async()=>{const f=copy(),before=JSON.stringify(f.source),v=viewer(f.source);try{await v.setElementContent(f.descriptor,{...options,sourceModel:structuredClone(f.source)});assert.equal(v.elementContentDiagnostic,null);const meshes=v.elementContentLayer.group.children,face=meshes.find(o=>o.isMesh),label=meshes.find(o=>o.isSprite);assert.ok(face&&label);assert.equal(face.userData.sourceFace,0);assert.equal(label.userData.sourceIndex,0);const entry=f.descriptor.entries[0],all=v.surfaceGeometry.getAttribute('position').array,expected=v.triangles.flatMap((t,i)=>t.face===entry.index?Array.from(all.subarray(i*9,i*9+9)):[]);assert.deepEqual(Array.from(face.geometry.getAttribute('position').array),expected);for(let i=3,a=face.geometry.getAttribute('color').array;i<a.length;i+=4)assert.ok(Math.abs(a[i]-147/255)<1e-7);assert.ok((await v.prepareCapture()).elementContent.ready);assert.equal(JSON.stringify(f.source),before);v.setDisplay({angles:[21,7,13,0,0,0],projection:'orthographic',faces:true,edges:true});assert.equal(v.elementContentDiagnostic,null);assert.equal(face.geometry.attributes.position.count,v.elementContentLayer.group.children.find(o=>o.isMesh).geometry.attributes.position.count);}finally{v.clear();}});
test('late PNG decode after source/units replacement cannot publish and releases its bitmap',async()=>{const f=copy(),v=viewer(f.source);let release,entered;const gate=new Promise(resolve=>entered=resolve),bitmap=image(),decodeImage=()=>{entered();return new Promise(resolve=>release=()=>resolve(bitmap));},pending=v.setElementContent(f.descriptor,{makeCanvas,decodeImage});await gate;f.source.metadata.coordinateUnits='cm';release();await assert.rejects(pending,{name:'AbortError'});assert.equal(bitmap.closed,true);assert.equal(v.elementContentLayer.group.children.length,0);v.clear();});
test('capture waits for actual image readiness and cancellation after an ignored decoder is atomic',async()=>{const f=copy(),v=viewer(f.source);let release,entered;const gate=new Promise(resolve=>entered=resolve),c=new AbortController(),pending=v.setElementContent(f.descriptor,{makeCanvas,decodeImage:()=>{entered();return new Promise(resolve=>release=()=>resolve(image()));},signal:c.signal});await gate;const capture=v.prepareCapture({signal:c.signal});c.abort();release();await assert.rejects(pending,{name:'AbortError'});await assert.rejects(capture,{name:'AbortError'});assert.equal(v.elementContentLayer.group.children.length,0);v.clear();});
test('replaced model, literal null removal and malformed source anchors refuse/clear requested content',async()=>{const f=copy(),v=viewer(f.source);await v.setElementContent(f.descriptor,options);await v.setElementContent(null);assert.equal(v.elementContentLayer,null);const bad=structuredClone(f.descriptor);bad.entries[1].anchor[0]+=.1;await assert.rejects(v.setElementContent(bad,options),/anchor/);await assert.rejects(v.prepareCapture(),/anchor/);v.clear();});
