const test=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const {EventEmitter}=require('node:events');
const crypto=require('node:crypto');
const source=fs.readFileSync(path.join(__dirname,'../desktop/main.cjs'),'utf8');
const plain=x=>JSON.parse(JSON.stringify(x));

// Execute the REAL main-process entry inside a CommonJS wrapper. Electron,
// filesystem writes and process creation are mocked; no GUI/engine is launched.
async function boot(env={},platform='win32',initialSwitches={}){
  const windows=[],ipc=new Map(),writes=[],spawns=[],native=[],menus=[],errors=[];
  const app=new EventEmitter(),paths={userData:path.resolve(__dirname,'ordinary-profile')};let readyCalls=0;
  const switches=new Map(Object.entries(initialSwitches)),switchWrites=[];
  Object.assign(app,{commandLine:{hasSwitch:k=>switches.has(k),getSwitchValue:k=>switches.get(k)||'',appendSwitch:(k,value='')=>{switchWrites.push({key:k,value,readyCalls});switches.set(k,value);}},isPackaged:false,getPath:k=>paths[k],setPath:(k,p)=>paths[k]=p,getVersion:()=>'.14-fixture',whenReady:()=>{readyCalls++;return Promise.resolve();},quit:()=>native.push('quit'),exit:code=>native.push(['exit',code]),focus:()=>native.push('app.focus')});
  const dialog={};for(const name of ['showOpenDialog','showSaveDialog','showMessageBox'])dialog[name]=async()=>{native.push(name);return {canceled:true,filePaths:[],response:0};};for(const name of ['showOpenDialogSync','showSaveDialogSync','showMessageBoxSync','showErrorBox'])dialog[name]=()=>{native.push(name);return undefined;};
  class BrowserWindow extends EventEmitter{
    constructor(options){super();this.options=options;this.destroyed=false;this.visible=options.show!==false;this.fullscreen=false;this.webContents=new EventEmitter();this.webContents.mainFrame={};Object.assign(this.webContents,{setWindowOpenHandler:fn=>{this.popupHandler=fn;},setAudioMuted:value=>{this.muted=value;},send:(...args)=>{this.sent=args;},focus:()=>native.push('webContents.focus'),openDevTools:()=>native.push('webContents.openDevTools'),inspectElement:()=>native.push('webContents.inspectElement'),print:(_opts,callback)=>{native.push('native-print');callback(true);},printToPDF:async()=>{native.push('pdf');return Buffer.from('%PDF-fixture');}});windows.push(this);app.emit('browser-window-created',{},this);}
    show(){native.push('show');this.visible=true;this.focus();}showInactive(){native.push('showInactive');this.visible=true;}focus(){native.push('focus');}restore(){native.push('restore');}maximize(){native.push('maximize');}minimize(){native.push('minimize');}moveTop(){native.push('moveTop');}setFullScreen(v){native.push('fullscreen');this.fullscreen=v;}setKiosk(){native.push('kiosk');}setAlwaysOnTop(){native.push('alwaysOnTop');}setFocusable(){native.push('focusable');}setSkipTaskbar(){native.push('skipTaskbar');}flashFrame(){native.push('flashFrame');}isFullScreen(){return this.fullscreen;}isDestroyed(){return this.destroyed;}destroy(){this.destroyed=true;}close(){native.push('close');}hide(){this.visible=false;}loadFile(file){this.loaded=file;return Promise.resolve();}loadURL(url){this.loaded=url;return Promise.resolve();}
  }
  const electron={app,BrowserWindow,dialog,ipcMain:{handle:(name,fn)=>ipc.set(name,fn)},Menu:{buildFromTemplate:template=>{native.push('build-menu');return template;},setApplicationMenu:menu=>menus.push(menu)}};
  const storage={publish:async(file,project)=>{writes.push(['project',file,project]);return {path:file};}};
  const animationExports={begin:async(_options,file)=>({id:'session',path:file}),write:async()=>true,finish:async()=>true,abort:async()=>true,abortAll:async()=>true};
  const mockFs={writeFile:async(...args)=>writes.push(args),mkdir:async()=>{},lstat:async()=>{throw Object.assign(Error('missing'),{code:'ENOENT'});},stat:async()=>{throw Error('missing');},readFile:async()=>{throw Object.assign(Error('missing'),{code:'ENOENT'});},unlink:async()=>{},rename:async()=>{},realpath:async p=>p};
  function spawn(executable,args,options){spawns.push({executable,args,options});const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdout.setEncoding=()=>{};child.stderr.setEncoding=()=>{};child.kill=()=>{child.killed=true;};child.stdin=new EventEmitter();child.stdin.end=data=>{const request=JSON.parse(data);queueMicrotask(()=>child.stdout.emit('data',JSON.stringify({ok:true,result:request.op==='catalog'?[]:{model:{metadata:{}},path:request.params?.path}})+'\n'));};return child;}
  const requireMock=name=>name==='electron'?electron:name==='node:child_process'?{spawn}:name==='node:fs/promises'?mockFs:name==='node:path'?path:name==='node:crypto'?crypto:name==='./text-export.cjs'?{createTextExport:options=>require('../desktop/text-export.cjs').createTextExport({...options,io:mockFs})}:name==='./project-storage.cjs'?{createProjectStorage:()=>storage}:name==='./animation-export.cjs'?{createAnimationExportManager:()=>animationExports,validateExportOptions:o=>({name:'fixture',format:o.format})}:(()=>{throw Error('Unexpected import '+name);})();
  const context=vm.createContext({Buffer,console,setTimeout,clearTimeout,process:{env:{...env},platform,resourcesPath:path.resolve(__dirname,'resources'),stderr:{write:s=>errors.push(s)}}});const compiled=new vm.Script('(function(require,module,exports,__dirname){\n'+source+'\n})',{filename:'desktop/main.cjs'}).runInContext(context);const module={exports:{}};compiled(requireMock,module,module.exports,path.resolve(__dirname,'../desktop'));
  await new Promise(resolve=>setImmediate(resolve));
  const invoke=(name,...args)=>{const w=windows[0];return ipc.get(name)({sender:w.webContents,senderFrame:w.webContents.mainFrame},...args);};
  return {app,dialog,windows,native,menus,errors,ipc,writes,spawns,invoke,switches,switchWrites,get readyCalls(){return readyCalls;}};
}
const hiddenEnv=()=>({POLYTOPE_TEST_MODE:'hidden-no-focus',POLYTOPE_TEST_USER_DATA:path.resolve(__dirname,'hidden-fixture-profile')});
const svg='<svg width="100mm" height="120mm"></svg>';

test('hidden startup creates only a nonfocusable hidden sandbox window, with no ready-to-show activation',async()=>{
  const b=await boot(hiddenEnv()),w=b.windows[0];assert.equal(b.windows.length,1);assert.equal(w.options.show,false);assert.equal(w.options.focusable,false);assert.equal(w.options.skipTaskbar,true);assert.equal(w.options.alwaysOnTop,false);assert.equal(w.options.fullscreen,false);assert.equal(w.options.paintWhenInitiallyHidden,true);assert.equal(w.options.webPreferences.backgroundThrottling,false);assert.equal(w.options.webPreferences.disableDialogs,true);assert.equal(w.options.webPreferences.focusOnNavigation,false);assert.equal(w.options.webPreferences.disableHtmlFullscreenWindowResize,true);assert.equal(w.options.webPreferences.sandbox,true);assert.equal(w.options.webPreferences.contextIsolation,true);assert.equal(w.options.webPreferences.nodeIntegration,false);assert.equal(w.muted,true);assert.equal(w.listeners('ready-to-show').length,0);w.emit('ready-to-show');assert.deepEqual(b.native,[]);assert.deepEqual(b.menus,[null]);assert.equal(w.visible,false);assert.deepEqual(plain(w.popupHandler()),{action:'deny'});
});
test('window, app and webContents activation/devtools APIs cannot be enabled accidentally',async()=>{
  const b=await boot(hiddenEnv()),w=b.windows[0];for(const name of ['show','showInactive','focus','restore','maximize','minimize','moveTop','setFullScreen','setKiosk','setAlwaysOnTop','setFocusable','setSkipTaskbar','flashFrame'])assert.throws(()=>w[name](true),/hidden-no-focus/);for(const name of ['focusable','fullScreen','simpleFullScreen','kiosk'])assert.throws(()=>{w[name]=true;},/hidden-no-focus/);for(const name of ['focus','openDevTools','inspectElement'])assert.throws(()=>w.webContents[name](),/hidden-no-focus/);assert.throws(()=>b.app.focus(),/hidden-no-focus/);assert.equal(Object.getOwnPropertyDescriptor(w,'show').writable,false);assert.deepEqual(b.native,[]);await assert.rejects(b.invoke('fullscreen'),/hidden-no-focus/);
});
test('invalid opt-ins exit quietly before readiness, windows, menus or native error dialogs',async()=>{
  for(const [env,platform] of [[{POLYTOPE_TEST_MODE:'1'},'win32'],[{POLYTOPE_TEST_MODE:''},'win32'],[{POLYTOPE_TEST_MODE:'hidden-no-focus'},'win32'],[{...hiddenEnv(),POLYTOPE_TEST_USER_DATA:'relative'},'win32'],[{...hiddenEnv(),POLYTOPE_TEST_USER_DATA:path.resolve(__dirname,'ordinary-profile')},'win32'],[hiddenEnv(),'linux']]){const b=await boot(env,platform);assert.equal(b.readyCalls,0);assert.equal(b.windows.length,0);assert.deepEqual(b.menus,[]);assert.deepEqual(b.native,[['exit',2]]);assert.equal(b.errors.length,1);assert.match(b.errors[0],/POLYTOPE_TEST/);assert.throws(()=>b.dialog.showErrorBox('bad','bad'),/hidden-no-focus/);assert.deepEqual(b.native,[['exit',2]]);}
});
test('all async and sync native dialogs reject before calling originals; trusted IPC diagnoses missing stubs',async()=>{
  const b=await boot(hiddenEnv());for(const name of ['showOpenDialog','showSaveDialog','showMessageBox'])await assert.rejects(b.dialog[name](),/hidden-no-focus/);for(const name of ['showOpenDialogSync','showSaveDialogSync','showMessageBoxSync','showErrorBox'])assert.throws(()=>b.dialog[name](),/hidden-no-focus/);for(const name of ['open','save','import-tour','export-tour','library','save-net-pdf','save-packed-net-pdf','animation-begin'])await assert.rejects(b.invoke(name,name==='animation-begin'?{format:'png'}:{}),/hidden-no-focus/);assert.deepEqual(b.native,[]);assert.equal(b.windows.length,1);assert.equal(b.writes.length,0);
});
test('existing explicit dialog stubs work without a renderer arbitrary-path bypass',async()=>{
  const b=await boot(hiddenEnv()),file=path.resolve(__dirname,'stub-destination.polyproj');b.dialog.showSaveDialog=async()=>({canceled:false,filePath:file});const saved=await b.invoke('save',{documents:[]});assert.equal(saved.path,file);assert.equal(b.writes[0][1],file);b.dialog.showOpenDialog=async()=>({canceled:true,filePaths:[]});assert.equal(await b.invoke('open'),null);assert.deepEqual(b.native,[]);await assert.rejects(b.ipc.get('save')({sender:{},senderFrame:{}},{}),/Untrusted/);assert.equal(b.writes.length,1);
});
test('both PDF document paths remain hidden/nonfocusable and never invoke native printing',async()=>{
  const b=await boot(hiddenEnv());b.dialog.showSaveDialog=async()=>({canceled:false,filePath:path.resolve(__dirname,'mock.pdf')});await b.invoke('save-net-pdf',svg);await b.invoke('save-packed-net-pdf',[svg,svg]);assert.equal(b.windows.length,3);for(const w of b.windows){assert.equal(w.options.show,false);assert.equal(w.options.focusable,false);assert.equal(w.options.skipTaskbar,true);assert.equal(w.options.webPreferences.disableDialogs,true);assert.equal(w.options.webPreferences.backgroundThrottling,false);}assert.equal(b.windows[1].options.webPreferences.javascript,false);assert.equal(b.windows[2].options.webPreferences.javascript,false);assert.equal(b.windows[1].destroyed,true);assert.equal(b.windows[2].destroyed,true);assert.deepEqual(b.native,['pdf','pdf']);assert.equal(b.writes.length,2);
});
test('both native print paths reject without opening printer UI and dispose their hidden documents',async()=>{
  const b=await boot(hiddenEnv());await assert.rejects(b.invoke('print',svg),/Native printing.*hidden-no-focus/);await assert.rejects(b.invoke('print-packed-nets',[svg]),/Native printing.*hidden-no-focus/);assert.equal(b.windows.length,3);assert.equal(b.windows[1].destroyed,true);assert.equal(b.windows[2].destroyed,true);assert.deepEqual(b.native,[]);
});
test('explicit per-window print callback stubs remain supported for headless IPC tests',async()=>{
  const b=await boot(hiddenEnv());let calls=0;b.app.on('browser-window-created',(_e,w)=>{w.webContents.print=(_options,callback)=>{calls++;callback(true);};});assert.equal(await b.invoke('print',svg),true);assert.equal(await b.invoke('print-packed-nets',[svg]),true);assert.equal(calls,2);assert.deepEqual(b.native,[]);
});
test('dirty hidden close avoids confirmation; webview attachment/unload prevention never activates windows',async()=>{
  const b=await boot(hiddenEnv()),w=b.windows[0];await b.invoke('dirty',true);let prevented=0;await Promise.all(w.listeners('close').map(fn=>fn({preventDefault:()=>prevented++})));assert.equal(prevented,0);for(const name of ['will-attach-webview','will-prevent-unload'])w.webContents.emit(name,{preventDefault:()=>prevented++});assert.equal(prevented,2);assert.deepEqual(b.native,[]);
});
test('engine process console hiding remains enabled and read-only mode evidence is main-process-only',async()=>{
  const b=await boot(hiddenEnv());assert.deepEqual(plain(await b.invoke('engine',{op:'catalog'})),[]);assert.equal(b.spawns.length,1);assert.equal(b.spawns[0].options.windowsHide,true);assert.deepEqual(plain(b.spawns[0].options.stdio),['pipe','pipe','pipe']);assert.equal(b.app.polytopeQualification.mode,'hidden-no-focus');assert.equal(b.app.polytopeQualification.engineWindowsHide,true);assert.equal(b.app.polytopeQualification.profile,hiddenEnv().POLYTOPE_TEST_USER_DATA);assert.equal(Object.isFrozen(b.app.polytopeQualification),true);assert.equal(Object.getOwnPropertyDescriptor(b.app,'polytopeQualification').writable,false);assert.equal(b.ipc.has('qualification'),false);assert.deepEqual(b.native,[]);
});
test('ordinary application behavior retains ready-to-show, native menu/dialogs, printing and dirty confirmation',async()=>{
  const b=await boot(),w=b.windows[0];assert.equal(w.options.focusable,undefined);assert.equal(w.options.skipTaskbar,undefined);assert.equal(w.options.webPreferences.disableDialogs,undefined);assert.equal(w.options.webPreferences.backgroundThrottling,undefined);assert.equal(b.app.polytopeQualification,undefined);assert.equal(b.menus[0].length,4);w.emit('ready-to-show');assert.equal(w.visible,true);assert.ok(b.native.includes('show'));assert.ok(b.native.includes('focus'));await b.invoke('open');assert.ok(b.native.includes('showOpenDialog'));assert.equal(await b.invoke('print',svg),true);assert.ok(b.native.includes('native-print'));await b.invoke('dirty',true);let prevented=0;await Promise.all(w.listeners('close').map(fn=>fn({preventDefault:()=>prevented++})));assert.equal(prevented,1);assert.ok(b.native.includes('showMessageBox'));
});
test('all application BrowserWindow construction flows through the guarded constructor',()=>{assert.equal((source.match(/new BrowserWindow\(/g)||[]).length,1);assert.equal((source.match(/createAppWindow\(\{/g)||[]).length,3);assert.equal(/shell\.|new Notification|app\.on\(['"]activate|second-instance/.test(source),false);});
test('hidden occlusion scheduling flags are applied before readiness without unrelated priority or security changes',async()=>{
  const b=await boot(hiddenEnv());assert.deepEqual(b.switchWrites,[{key:'disable-backgrounding-occluded-windows',value:'',readyCalls:0},{key:'disable-features',value:'CalculateNativeWinOcclusion',readyCalls:0}]);assert.deepEqual(plain(b.app.polytopeQualification.scheduling),{occludedWindowBackgrounding:false,nativeWinOcclusion:false,disableFeatures:'CalculateNativeWinOcclusion'});assert.equal(Object.isFrozen(b.app.polytopeQualification.scheduling),true);
});
test('hidden mode preserves supplied switch values and disabled features without duplicate occlusion entries',async()=>{
  const supplied={'disable-features':'FeatureA:mode/test,FeatureB','example-switch':'keep'},b=await boot(hiddenEnv(),'win32',supplied);assert.equal(b.switches.get('disable-features'),'FeatureA:mode/test,FeatureB,CalculateNativeWinOcclusion');assert.equal(b.switches.get('example-switch'),'keep');
  const existing={'disable-features':'FeatureA, CalculateNativeWinOcclusion ,FeatureB','disable-backgrounding-occluded-windows':'caller-value'},c=await boot(hiddenEnv(),'win32',existing);assert.deepEqual(c.switchWrites,[]);assert.equal(c.switches.get('disable-features'),existing['disable-features']);assert.equal(c.switches.get('disable-backgrounding-occluded-windows'),'caller-value');
});
test('ordinary profile isolation and invalid modes never amend command line scheduling',async()=>{
  const supplied={'disable-features':'ExistingFeature','example-switch':'keep'};for(const env of [{},{POLYTOPE_TEST_USER_DATA:hiddenEnv().POLYTOPE_TEST_USER_DATA},{POLYTOPE_TEST_MODE:'bad'}]){const b=await boot(env,'win32',supplied);assert.deepEqual(b.switchWrites,[]);assert.deepEqual(Object.fromEntries(b.switches),supplied);}
});
