import test from 'node:test';
import assert from 'node:assert/strict';
import {samePackedDisplayOwners,PACKED_OWNER_FIELDS} from '../ui/packed-owner-comparison.mjs';
import {legacySameTypedDisplayOwners} from './fixtures/legacy-surface-colors.mjs';

function fixture(n=3){
  const modelId='literal-source',fingerprint='a'.repeat(64),owner={modelId,fingerprint,sourceKey:JSON.stringify([modelId,fingerprint]),frameKey:'poseA',generation:1};
  return {owner,...Object.fromEntries(Object.entries(PACKED_OWNER_FIELDS).map(([key,Type])=>[key,Type.from({length:n},(_,i)=>key.endsWith('Cells')||key==='cellIds'?i-1:i)])),positions:new Float32Array(n*3),normals:new Float32Array(n*9),vertexVisible:new Uint8Array(n).fill(1),triangleResolution:new Uint8Array(n).fill(1)};
}
test('every exact ordered owner array agrees with the frozen old algorithm',()=>{const a=fixture(),b=structuredClone(a);assert.equal(samePackedDisplayOwners(a,b),true);assert.equal(legacySameTypedDisplayOwners(a,b),true);for(const key of Object.keys(PACKED_OWNER_FIELDS)){const b=structuredClone(a);b[key][b[key].length-1]++;assert.equal(samePackedDisplayOwners(a,b),false,key);assert.equal(legacySameTypedDisplayOwners(a,b),false,key);}});
test('coordinates/normals/quality/resolution/pose are excluded exactly as before',()=>{const a=fixture(),b=structuredClone(a);b.positions.fill(20);b.normals.fill(-1);b.vertexVisible.fill(0);b.triangleResolution.fill(4);Object.assign(b.owner,{frameKey:'poseB',generation:9,jobId:10});b.phase='capture';assert.equal(samePackedDisplayOwners(a,b),true);assert.equal(legacySameTypedDisplayOwners(a,b),true);});
test('ordered repeated instance IDs and source edge/face/cell IDs cannot be deduplicated or reordered',()=>{for(const key of Object.keys(PACKED_OWNER_FIELDS)){const a=fixture(5),b=structuredClone(a);b[key].reverse();assert.equal(samePackedDisplayOwners(a,b),false,key);}const a=fixture(5),b=structuredClone(a);a.triangleInstanceIds.set([0,0,1,1,2]);b.triangleInstanceIds.set([0,1,0,1,2]);assert.equal(samePackedDisplayOwners(a,b),false);});
test('source ID/fingerprint/key must remain mutually bound; matching naked arrays do not prove a source',()=>{const a=fixture();for(const edit of [b=>b.owner.modelId='other',b=>b.owner.fingerprint='b'.repeat(64),b=>b.owner.sourceKey='other',b=>delete b.owner.fingerprint,b=>delete b.owner.modelId,b=>delete b.owner.sourceKey,b=>b.owner.fingerprint='invalid',b=>b.owner.modelId='x'.repeat(513)]){const b=structuredClone(a);edit(b);assert.equal(samePackedDisplayOwners(a,b),false);}assert.equal(samePackedDisplayOwners(null,a),false);assert.equal(samePackedDisplayOwners(a,null),false);});
test('another valid model source or fingerprint refuses even with all owner slots identical',()=>{const a=fixture(),b=structuredClone(a);b.owner.modelId='other';b.owner.sourceKey=JSON.stringify([b.owner.modelId,b.owner.fingerprint]);assert.equal(samePackedDisplayOwners(a,b),false);b.owner.modelId=a.owner.modelId;b.owner.fingerprint='b'.repeat(64);b.owner.sourceKey=JSON.stringify([b.owner.modelId,b.owner.fingerprint]);assert.equal(samePackedDisplayOwners(a,b),false);});
test('null source IDs follow the typed-display identity convention',()=>{const a=fixture(),b=structuredClone(a);for(const x of [a,b]){x.owner.modelId=null;x.owner.sourceKey=JSON.stringify([null,x.owner.fingerprint]);}assert.equal(samePackedDisplayOwners(a,b),true);});
test('length/type/missing-field/detached/shared representations fail closed',()=>{for(const key of Object.keys(PACKED_OWNER_FIELDS)){const a=fixture(),Type=PACKED_OWNER_FIELDS[key];for(const changed of [new Type(2),Array.from(a[key]),new (Type===Uint32Array?Int32Array:Uint32Array)(a[key]),new Type(new SharedArrayBuffer(12)),new class extends Type{}(3),undefined]){const b=structuredClone(a);b[key]=changed;assert.equal(samePackedDisplayOwners(a,b),false,key);}const b=structuredClone(a);structuredClone(b[key].buffer,{transfer:[b[key].buffer]});assert.equal(samePackedDisplayOwners(a,b),false,key);}});
test('zero-length detached owner slots do not masquerade as valid empty geometry',()=>{const a=fixture(0),b=structuredClone(a);assert.equal(samePackedDisplayOwners(a,b),true);structuredClone(b.faceIds.buffer,{transfer:[b.faceIds.buffer]});assert.equal(samePackedDisplayOwners(a,b),false);});
test('100k owner comparisons avoid TypedArray.every callbacks and never mutate either snapshot',()=>{const a=fixture(100000),b=structuredClone(a),before=a.faceIds.slice(),u=Uint32Array.prototype.every,i=Int32Array.prototype.every;try{Uint32Array.prototype.every=Int32Array.prototype.every=()=>{throw Error('Unexpected callback comparison');};assert.equal(samePackedDisplayOwners(a,b),true);b.triangleInstanceIds[99999]++;assert.equal(samePackedDisplayOwners(a,b),false);}finally{Uint32Array.prototype.every=u;Int32Array.prototype.every=i;}assert.deepEqual(a.faceIds,before);assert.equal(a.triangleInstanceIds[99999],99999);});
test('aggregate owner buffers remain under the display allocation bound',()=>{const a=fixture(),b=structuredClone(a);a.vertexIds=b.vertexIds=new Uint32Array(32*1024*1024/4+1);assert.equal(samePackedDisplayOwners(a,b),false);});
