import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {legacySurfaceColors} from './fixtures/legacy-surface-colors.mjs';
import {packSurfaceColors,PACKED_COLOR_LIMITS} from '../ui/packed-surface-colors.mjs';

function fixture(){
  const model={id:'literal-source',fingerprint:'a'.repeat(64),dimension:4,vertices:[[0,0,0,0],[1,0,0,0],[0,1,0,0],[0,0,1,0]],edges:[[0,1],[1,2],[2,3],[3,0]],faces:[[0,1,2],[0,2,3],[0,1,3],[1,2,3]],cells:[[0,1],[0,2,3],[0,1,2,3]],metadata:{offColors:{faces:[{encoding:'byte',values:[200,100,50,128]},null,{encoding:'unit',values:[.2,.3,.4,.99999999]},null],cells:[{encoding:'unit',values:[.1,.6,.8,.25]},{encoding:'byte',values:[3,70,240,200]},{encoding:'unit',values:[.8,.3,.1,.7]}]}}};
  const packed={owner:{modelId:model.id,fingerprint:model.fingerprint,sourceKey:JSON.stringify([model.id,model.fingerprint])},sourceCounts:Object.fromEntries(['vertices','edges','faces','cells'].map(k=>[k,model[k].length])),faceIds:new Uint32Array([0,1,1,2,2,3,0,3]),cellIds:new Int32Array([-1,-1,2,-1,1,2,1,-1])};
  const visibility={faceOwners:[[0,1,2],[0,2],[1,2],[1,2]],activeCellSet:new Set([0,1,2])};return {model,packed,visibility};
}
export function referenceColors(f,mode){const v={model:f.model,stereographicGeometry:{packed:f.packed},renderTriangles:{length:f.packed.faceIds.length},visibility:f.visibility,surfaceGeometry:new THREE.BufferGeometry(),surface:{material:new THREE.MeshPhongMaterial()}};legacySurfaceColors.call(v,mode);const result={colors:v.surfaceGeometry.getAttribute('color').array.slice(),vertexAlpha:v.surfaceVertexAlpha};v.surfaceGeometry.dispose();v.surface.material.dispose();return result;}
const bits=a=>new Uint32Array(a.buffer,a.byteOffset,a.length);
function equivalent(f,mode,options){const expected=referenceColors(f,mode),actual=packSurfaceColors(f.model,f.packed,f.visibility,mode,options);assert.deepEqual(bits(actual.colors.subarray(0,f.packed.faceIds.length*12)),bits(expected.colors));assert.equal(actual.vertexAlpha,expected.vertexAlpha);return actual;}

for(const mode of ['source','face','cell'])test(`${mode} matches the frozen pre-optimization method bit-for-bit with mixed source overrides and explicit/negative owners`,()=>{const f=fixture(),before=structuredClone({model:f.model,packed:f.packed});equivalent(f,mode);assert.deepEqual(f.model,before.model);assert.deepEqual(f.packed,before.packed);});
test('hidden-cell fallback chooses the first active owner, while explicit owner remains authoritative',()=>{const f=fixture();for(const active of [[],[2],[1,2]]){f.visibility.activeCellSet=new Set(active);for(const mode of ['source','cell'])equivalent(f,mode);}f.visibility.faceOwners[0].reverse();f.visibility.faceOwners[3].reverse();equivalent(f,'cell');});
test('no cells/default slate color and unowned faces reproduce the original renderer',()=>{const f=fixture();f.model.cells=[];f.packed.sourceCounts.cells=0;f.packed.cellIds.fill(-1);f.visibility={faceOwners:Array.from({length:4},()=>[]),activeCellSet:new Set()};delete f.model.metadata;for(const mode of ['source','cell','face'])equivalent(f,mode);});
test('RGB without alpha, source face precedence, and ignored source attributes in other modes',()=>{const f=fixture();f.model.metadata.offColors.faces[0]={encoding:'unit',values:[.1,.2,.3]};f.model.metadata.offColors.cells[1]={encoding:'byte',values:[255,0,100]};for(const mode of ['source','face','cell'])equivalent(f,mode);});
test('face override does not evaluate a shadowed source-cell color',()=>{const f=fixture();f.packed.faceIds.fill(0);f.packed.cellIds.fill(1);Object.defineProperty(f.model.metadata.offColors.cells,1,{get(){throw Error('Shadowed cell color should not be read.');}});equivalent(f,'source');});
test('double-precision alpha below1 still marks transparency when Float32 rounds it to1',()=>{const f=fixture();f.packed.faceIds.fill(2);f.packed.cellIds.fill(-1);const p=equivalent(f,'source');assert.equal(p.vertexAlpha,true);assert.equal(p.colors[3],1);});
test('caller-owned capacity is reused, unused suffix preserved, and output never aliases worker arrays',()=>{const f=fixture(),target=new Float32Array(f.packed.faceIds.length*12+24).fill(42);const r=equivalent(f,'source',{target});assert.strictEqual(r.colors,target);assert.ok(target.subarray(f.packed.faceIds.length*12).every(x=>x===42));const alias=new Float32Array(f.packed.faceIds.buffer);assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility,'source',{target:alias}),/capacity|aliases/);});
test('adequate-capacity aliases of worker geometry are rejected before any write',()=>{const f=fixture();f.packed.positions=new Float32Array(f.packed.faceIds.length*12);const before=f.packed.positions.slice();assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility,'source',{target:f.packed.positions}),/aliases/);assert.deepEqual(f.packed.positions,before);});
test('stale source identity/counts and invalid final owner refuse atomically',()=>{for(const edit of [f=>f.packed.owner.modelId='other',f=>f.packed.owner.fingerprint='b'.repeat(64),f=>f.packed.owner.sourceKey='other',f=>f.packed.sourceCounts.faces++,f=>f.packed.faceIds[f.packed.faceIds.length-1]=4,f=>f.packed.cellIds[f.packed.cellIds.length-1]=3,f=>f.packed.cellIds[0]=-2]){const f=fixture(),target=new Float32Array(96).fill(7);edit(f);assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility,'source',{target}),/bound|stale|ownership/);assert.ok(target.every(x=>x===7));}});
test('malformed source color encountered late leaves the existing visible color target unchanged',()=>{const f=fixture();f.model.metadata.offColors.cells[2]={encoding:'unit',values:[Infinity,0,0]};const target=new Float32Array(96).fill(9);assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility,'source',{target}),/Source colors/);assert.ok(target.every(x=>x===9));});
test('source/palette/patch/owner-reference allocation limits are bounded and unknown modes refuse',()=>{for(const limits of [{patches:7},{faces:3},{cells:2},{bytes:100},{ownerReferences:1},{patches:PACKED_COLOR_LIMITS.patches+1},{unknown:1}]){const f=fixture();assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility,'source',{limits}),/limit|Limits/);}const f=fixture();assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility,'unknown'),/mode/);});
test('ordinary Float32 target and native typed owner representations are required',()=>{for(const edit of [f=>f.packed.faceIds=new Uint16Array(8),f=>f.packed.cellIds=new Int32Array(7),f=>f.packed.faceIds=new Uint32Array(new SharedArrayBuffer(32)),f=>f.packed.cellIds=new class extends Int32Array{}(8),f=>{structuredClone(f.packed.faceIds.buffer,{transfer:[f.packed.faceIds.buffer]});}]){const f=fixture();edit(f);assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility),/buffer|detached|limit/);}const f=fixture();assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility,'source',{target:new Float64Array(96)}),/buffer/);});
test('bad visibility or active source owner is refused before recoloring',()=>{for(const edit of [f=>f.visibility.faceOwners.pop(),f=>f.visibility.faceOwners[3]=[3],f=>f.visibility.activeCellSet.add(3),f=>f.visibility.activeCellSet=[0,1],f=>f.visibility.faceOwners[0]=null]){const f=fixture(),target=new Float32Array(96).fill(3);edit(f);assert.throws(()=>packSurfaceColors(f.model,f.packed,f.visibility,'source',{target}),/Visibility|visibility|owner|ownership/);assert.ok(target.every(x=>x===3));}});
test('100k patches match production with no per-patch Map/set or triangle-record expansion',()=>{const f=fixture(),n=100000;f.packed.faceIds=Uint32Array.from({length:n},(_,i)=>i%4);f.packed.cellIds=new Int32Array(n).fill(-1);const expected=referenceColors(f,'source'),oldGet=Map.prototype.get,oldSet=Float32Array.prototype.set;let actual;try{Map.prototype.get=()=>{throw Error('Unexpected Map lookup');};Float32Array.prototype.set=()=>{throw Error('Unexpected TypedArray.set');};actual=packSurfaceColors(f.model,f.packed,f.visibility);}finally{Map.prototype.get=oldGet;Float32Array.prototype.set=oldSet;}assert.deepEqual(bits(actual.colors),bits(expected.colors));assert.equal(actual.vertexAlpha,expected.vertexAlpha);});
test('zero patches produce no alpha and support an empty reusable target',()=>{const f=fixture();f.packed.faceIds=new Uint32Array();f.packed.cellIds=new Int32Array();const target=new Float32Array();const r=equivalent(f,'source',{target});assert.strictEqual(r.colors,target);assert.equal(r.vertexAlpha,false);});
