import test from 'node:test';
import assert from 'node:assert/strict';
import {Worker} from 'node:worker_threads';
import * as THREE from 'three';
import {prepareStereographicWorkerGeometry as prepare,computeStereographicWorkerGeometry as compute,runStereographicWorkerJob} from '../ui/stereographic-worker-geometry.mjs';
import {prepareStereographicWorkerGeometry as oldPrepare,computeStereographicWorkerGeometry as oldCompute} from '../artifacts/frozen-0.21.0-release-qualified-source/source/ui/stereographic-worker-geometry.mjs';
import {sphericalSpanNormal,stereographicPatchNormals,stereographicPatchCornerOrder} from '../ui/stereographic-normals.mjs';
import {stereoDisplayGeometry} from '../ui/viewer-stereographic.mjs';
import {packSurfaceColors} from '../ui/packed-surface-colors.mjs';
import {createStereographicTypedDisplay} from '../ui/stereographic-typed-display.mjs';
import {Viewer} from '../ui/viewer.js';
import {planStereographicQuality} from '../ui/stereographic-quality.mjs';
const thin=[[0,.5,0,-.9375],[.125,.500030517578125,0,-.9335861203726381],[.25,.5,0,-.921875]],pole=[[1,0,0,1],[-.5,1,0,1],[-.5,-1,0,1]],sub=(a,b)=>a.map((x,i)=>x-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),unit=p=>p.map(x=>x/Math.hypot(...p));
function analyticDifferential(raw,u=1/3,v=1/3){const U=sub(raw[1],raw[0]),V=sub(raw[2],raw[0]),p=raw[0].map((x,i)=>x+u*U[i]+v*V[i]),rho=Math.hypot(...p),d=rho-p[3];const derivative=t=>p.slice(0,3).map((x,i)=>(t[i]*d-x*(dot(p,t)/rho-t[3]))/(d*d));return unit(cross(derivative(U),derivative(V)));}
function fixture(raw=thin){const model={id:'signed-witness',fingerprint:'a'.repeat(64),dimension:4,embeddingDimension:4,interpretation:'generalized-complex',vertices:structuredClone(raw),edges:[[0,1],[1,2],[2,0]],faces:[[0,1,2]],cells:[],metadata:{units:'mm',offColors:{faces:[{encoding:'byte',values:[31,127,239,73]}]}}};return {model,normalized:raw,edges:model.edges,triangles:[{face:0,vertices:[0,1,2]}],visibility:{vertices:[true,true,true],edges:[true,true,true],faces:[true]},conformingSurfaces:true};}
function assertWinding(g){for(let i=0;i<g.triangles.length;i+=9){const points=[0,1,2].map(k=>Array.from(g.triangles.slice(i+k*3,i+k*3+3))),normal=[0,1,2].map(k=>Array.from(g.normals.slice(i+k*3,i+k*3+3))),chord=cross(sub(points[1],points[0]),sub(points[2],points[0])),average=normal[0].map((x,j)=>x+normal[1][j]+normal[2][j]);assert.ok(dot(chord,average)>0);}}
function multiset(g,i){return [0,1,2].map(k=>JSON.stringify(Array.from(g.triangles.slice(i+k*3,i+k*3+3)))).sort();}
function job(input){return {type:'geometry-job',version:1,jobId:19,token:3,generation:7,sourceKey:'signed-witness-source',frameKey:'identity-pose',phase:'capture',quality:planStereographicQuality({cameraProjection:'orthographic',cssHeight:900,orthographicHalfHeight:6,zoom:1,phase:'capture'}),geometry:input};}
test('actual corrected worker fixes retained no-pole sign and DoubleSide chord front together',()=>{const f=fixture(),before=JSON.stringify(f),input=prepare(f),result=compute(input),old=oldCompute(oldPrepare(f));assert.equal(result.complete,true);assert.equal(result.geometry.triangles.length,9);const expected=analyticDifferential(thin);for(let k=0;k<3;k++){assert.ok(dot(Array.from(result.geometry.normals.slice(k*3,k*3+3)),expected)>.99999999);assert.ok(dot(Array.from(old.geometry.normals.slice(k*3,k*3+3)),expected)<-.99999999);}assertWinding(result.geometry);assert.deepEqual(multiset(result.geometry,0),multiset(old.geometry,0));assert.equal(JSON.stringify(f),before);});
test('negative-gradient orientation is independent of child order; only reversing raw source reverses it',()=>{const raw=[[1,0,0,0],[0,1,0,0],[0,0,1,0]],p=[[1,0,0],[Math.SQRT1_2,Math.SQRT1_2,0],[.5,.5,Math.SQRT1_2]],span=sphericalSpanNormal(raw),normal=stereographicPatchNormals(p,span),reversed=stereographicPatchNormals([...p].reverse(),span);assert.deepEqual(reversed,[...normal].reverse());assert.deepEqual(stereographicPatchCornerOrder(p,normal),[0,1,2]);assert.deepEqual(stereographicPatchCornerOrder([...p].reverse(),reversed),[0,2,1]);const flip=stereographicPatchNormals(p,sphericalSpanNormal([raw[0],raw[2],raw[1]]));normal.forEach((n,i)=>assert.ok(dot(n,flip[i])<-.999999999));});
test('shared planar source-face fan normals never flip across locally backward projected chords',()=>{const raw=[...thin,[.125,.6,0,-.92]],f=fixture(raw);f.model.faces=[[0,1,2,3]];f.triangles=[{face:0,vertices:[0,1,2]},{face:0,vertices:[0,2,3]}];f.visibility.vertices=[true,true,true,true];const input=prepare(f),r=compute(input);assert.ok(r.geometry.triangles.length>=18);assertWinding(r.geometry);for(let i=0;i<r.geometry.normals.length;i+=3)assert.ok(r.geometry.normals[i+2]>.99999999);assert.deepEqual([...new Set(r.geometry.faceIds)],[0]);});
test('ordinary and rotated spherical support keeps differential sign and normals/chords consistent',()=>{for(const raw of [[[1,0,0,0],[0,1,0,0],[0,0,1,0]],[[.8660254037844386,0,0,.5],[0,1,0,0],[0,0,1,0]]]){const f=fixture(raw),input=prepare(f),r=compute(input);assert.equal(r.complete,true);assertWinding(r.geometry);const span=sphericalSpanNormal(raw);for(let i=0;i<r.geometry.triangles.length;i+=3){const p=Array.from(r.geometry.triangles.slice(i,i+3)),expected=unit(span.slice(0,3).map((x,j)=>-x-span[3]*p[j]));assert.ok(dot(Array.from(r.geometry.normals.slice(i,i+3)),expected)>.9999999);}}});
test('native points/arcs/owner/color buffers are unchanged while triangle vertex order is presentation-only',()=>{const f=fixture(),input=prepare(f),r=compute(input),o=oldCompute(oldPrepare(f));for(const key of ['positions','vertexIds','vertexFaces','vertexCells','vertexVisible','segments','edgeIds','edgeFaces','edgeCells','edgeInstanceIds','edgeResolution','faceIds','cellIds','triangleIds','triangleInstanceIds','triangleResolution'])assert.deepEqual(r.geometry[key],o.geometry[key],key);const packed={owner:{modelId:f.model.id,fingerprint:f.model.fingerprint,sourceKey:JSON.stringify([f.model.id,f.model.fingerprint])},sourceCounts:input.sourceCounts,faceIds:r.geometry.faceIds,cellIds:r.geometry.cellIds},colors=packSurfaceColors(f.model,packed,{faceOwners:[[]],activeCellSet:new Set()},'source'),rgb=new THREE.Color().setRGB(31/255,127/255,239/255,THREE.SRGBColorSpace);for(let i=0;i<colors.colors.length;i+=4)for(let k=0;k<4;k++)assert.ok(Math.abs(colors.colors[i+k]-[rgb.r,rgb.g,rgb.b,73/255][k])<1e-7);assert.equal(colors.vertexAlpha,true);assert.throws(()=>packSurfaceColors({...f.model,id:'replacement'},packed,{faceOwners:[[]],activeCellSet:new Set()},'source'),/bound/);});
test('real dedicated Worker transfer and synchronous primitive fallback agree on signed winding and provenance',async()=>{const f=fixture(),input=prepare(f),request=job(input),expected=runStereographicWorkerJob(request),worker=new Worker(new URL('./stereographic-dense-worker-entry.mjs',import.meta.url));try{await new Promise((resolve,reject)=>{worker.once('error',reject);worker.once('message',resolve);});const response=await new Promise((resolve,reject)=>{worker.once('error',reject);worker.once('message',resolve);worker.postMessage(request);});assert.equal(response.type,'geometry-result');assert.equal(response.complete,true);for(const key of ['triangles','normals','segments','positions','faceIds','triangleInstanceIds'])assert.deepEqual(response.geometry[key],expected.geometry[key]);assert.equal(response.sourceKey,request.sourceKey);assert.equal(response.frameKey,request.frameKey);assertWinding(response.geometry);const sync=stereoDisplayGeometry(f.normalized,f.edges,f.triangles,f.visibility,null,[],{tolerance:request.quality.tolerance});assert.deepEqual(new Float32Array(sync.triangles.flatMap(t=>t.normals.flat())),response.geometry.normals);assert.deepEqual(new Float32Array(sync.triangles.flatMap(t=>t.points.flat())),response.geometry.triangles);}finally{await worker.terminate();}});
test('pole and cap partial receipts still refuse exact capture after signed orientation fix',()=>{for(const options of [{limits:{triangles:1}},{maxDepth:0}]){const r=compute(prepare(fixture(pole)),options);assert.equal(r.complete,false);assert.ok(r.unresolvedTriangles||r.clippedTriangles||r.omittedTriangles);assert.ok(r.geometry.diagnostics.length);}assert.equal(stereographicPatchCornerOrder([[0,0,0],[1,0,0],[2,0,0]],[[0,0,1],[0,0,1],[0,0,1]]),null);});
test('actual Viewer unavailable-worker fallback publishes oriented GPU attributes and original face picking receipt',()=>{
  const f=fixture(),model=f.model;model.vertices=[...thin,...thin.map(p=>p.map(x=>-x)),[1,0,0,0],[-1,0,0,0],[0,1,0,0],[0,-1,0,0],[0,0,1,0],[0,0,-1,0],[0,0,0,1],[0,0,0,-1]];const before=JSON.stringify(model),v=Object.create(Viewer.prototype);v.group=new THREE.Group();v.setModel(model);v.cameraProjection='orthographic';v.orthographicHalfHeight=6;v.camera=new THREE.OrthographicCamera(-6,6,6,-6,.01,1000);v.orthographicCamera=v.camera;v.perspectiveCamera=new THREE.PerspectiveCamera(38,1,.01,1000);v.camera.position.set(0,0,8);v.camera.lookAt(0,0,0);v.camera.updateMatrixWorld();v.controls={target:new THREE.Vector3(),update(){}};v.renderer={domElement:{getBoundingClientRect:()=>({width:900,height:900})},render(){}};v.stereographicWorkerFactory=()=>null;
  try{v.setDisplay({projection:'stereographic',cameraProjection:'orthographic',faces:true,edges:true,vertices:true,surfaceColors:'source',surfaceOpacity:1,pickKind:'face'});const p=v.stereographicGeometry.packed;assert.ok(p);assert.equal(p.complete,true);assertWinding(p);assert.strictEqual(v.surfaceGeometry.getAttribute('position').array,p.triangles);assert.strictEqual(v.surfaceGeometry.getAttribute('normal').array,p.normals);assert.strictEqual(v.publishedPickState.packedDisplay,p);assert.deepEqual(p.patchOwnerAt(0),{face:0,cell:undefined,sourceTriangle:0,sourceInstance:0});assert.equal(v.surface.material.side,THREE.DoubleSide);assert.equal(v.surface.material.flatShading,false);
    const colors=v.surfaceGeometry.getAttribute('color').array;for(let i=3;i<colors.length;i+=4)assert.ok(Math.abs(colors[i]-73/255)<1e-7);const center=[0,1,2].map(j=>(p.triangles[j]+p.triangles[j+3]+p.triangles[j+6])/3),ray=new THREE.Raycaster(new THREE.Vector3(center[0],center[1],1),new THREE.Vector3(0,0,-1)),hit=ray.intersectObject(v.surface)[0];assert.ok(hit);assert.equal(p.patchOwnerAt(hit.faceIndex).face,0);assert.equal(JSON.stringify(model),before);
  }finally{v.clear();}
});
