const { _electron: electron }=require('playwright');
const path=require('node:path');
const fs=require('node:fs/promises');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),artifacts=process.env.POLYTOPE_TEST_ARTIFACTS?path.resolve(process.env.POLYTOPE_TEST_ARTIFACTS):path.join(root,'artifacts');
async function main(){
  await fs.mkdir(artifacts,{recursive:true});
  const env={...process.env,POLYTOPE_TEST_USER_DATA:path.join(artifacts,'smoke-profile')};delete env.ELECTRON_RUN_AS_NODE;
  const packaged=process.env.POLYTOPE_TEST_EXECUTABLE;
  const app=await electron.launch({executablePath:packaged||require('electron'),args:packaged?[]:[root],cwd:root,env,timeout:30000});
  const page=await app.firstWindow();page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Renderer:',e.message);});
  page.on('console',message=>{if(message.type()==='error')console.error('Console:',message.text());});
  console.log('Window opened:',page.url());
  try{
    await page.waitForFunction(()=>document.getElementById('model-name')?.textContent==='Tesseract',null,{timeout:25000});
    console.log('Tesseract loaded.');
    await page.locator('#toggle-inspector').click();
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('8 vertices'));
    assert.equal(await page.locator('.count-block strong').nth(0).innerText(),'16');
    await page.screenshot({path:path.join(artifacts,'workspace-tesseract.png')});
    await page.locator('[data-key="cube"]').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Cube');
    await page.locator('[data-panel="construct"]').click();
    await page.locator('#make-dual').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Dual of Cube');
    assert.equal(await page.locator('.count-block strong').first().innerText(),'6');
    await page.locator('#undo').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Cube');
    await page.locator('#redo').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Dual of Cube');
    await page.locator('#undo').click();
    await page.locator('#truncation').fill('1/2');await page.locator('#truncate').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Rectification of Cube');
    assert.equal(await page.locator('.count-block strong').first().innerText(),'12');
    await page.locator('#undo').click();
    await page.locator('#expression').fill('1/3 + 1/6');await page.locator('#evaluate').click();
    await page.waitForFunction(()=>document.getElementById('expression-result').textContent.includes('rational exact'));
    await page.locator('[data-panel="info"]').click();
    await page.locator('#measurement-ids').fill('0, 1');await page.locator('#measure').click();
    await page.waitForFunction(()=>document.getElementById('measurement-result').textContent==='2 model-units');
    await page.locator('#viewport-layout').selectOption('split');
    await page.locator('#derived-mode').selectOption('net');
    await page.waitForFunction(()=>document.querySelector('#net-preview svg'));
    assert.equal(await page.locator('#net-preview polygon').count(),6);
    await page.screenshot({path:path.join(artifacts,'workspace-cube-net.png')});
    await page.locator('[data-panel="net"]').click();
    const hinge=await page.locator('#net-preview path[stroke-dasharray]').first().evaluate(p=>Number(p.nextElementSibling.dataset.netEdge));
    await page.locator('#net-edge').fill(String(hinge));await page.locator('#net-toggle-edge').click();
    await page.waitForFunction(()=>document.getElementById('net-summary').textContent.includes('2 connected pieces'));
    assert.equal(await page.locator('#net-preview g[data-net-component]').count(),2);
    await page.locator('#net-move-x').fill('12');await page.locator('#net-move-y').fill('-5');await page.locator('#net-angle').fill('23');await page.locator('#net-move').click();
    await page.waitForFunction(()=>document.getElementById('net-summary').dataset.edit==='2');
    await page.locator('#net-undo').click();await page.waitForFunction(()=>document.getElementById('net-summary').dataset.edit==='1');
    await page.locator('#net-undo').click();await page.waitForFunction(()=>document.getElementById('net-summary').textContent.includes('1 connected piece'));
    await page.locator('#net-redo').click();await page.waitForFunction(()=>document.getElementById('net-summary').textContent.includes('2 connected pieces'));
    await page.locator('#net-redo').click();await page.waitForFunction(()=>document.getElementById('net-summary').dataset.edit==='2');
    const dragPoint=await page.locator('#net-preview [data-net-face] polygon').first().evaluate(p=>{const points=Array.from(p.points),x=points.reduce((s,p)=>s+p.x,0)/points.length,y=points.reduce((s,p)=>s+p.y,0)/points.length;const screen=new DOMPoint(x,y).matrixTransform(p.getScreenCTM());return {x:screen.x,y:screen.y};});
    await page.mouse.move(dragPoint.x,dragPoint.y);await page.mouse.down();await page.mouse.move(dragPoint.x+25,dragPoint.y+18,{steps:5});await page.mouse.up();
    await page.waitForFunction(()=>document.getElementById('net-summary').dataset.edit==='3');
    await page.locator('#net-fold').evaluate(p=>{p.value='0.5';p.dispatchEvent(new Event('input',{bubbles:true}));});
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('Rigid net fold 50%'));
    await page.screenshot({path:path.join(artifacts,'workspace-net-fold-half.png')});
    await page.locator('#net-fold').evaluate(p=>{p.value='1';p.dispatchEvent(new Event('input',{bubbles:true}));});
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('source endpoint reconstructed'));
    await page.locator('#net-play').click();
    await page.waitForFunction(()=>document.getElementById('net-fold-value').textContent!=='100%');
    await page.locator('#net-play').click();
    await page.locator('#net-display').selectOption('layout');await page.waitForFunction(()=>!document.getElementById('net-preview').hidden);
    const pdfFile=path.join(artifacts,'smoke-net.pdf');
    await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},pdfFile);
    await page.locator('#export').click();await page.locator('#export-net-pdf').click();
    await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Exported calibrated net PDF'));
    assert.ok((await fs.readFile(pdfFile)).subarray(0,4).toString()==='%PDF');
    const projectFile=path.join(artifacts,'smoke.polyproj'),offFile=path.join(artifacts,'smoke.off');
    await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},projectFile);
    await page.locator('#save').click();
    await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Saved '));
    const saved=JSON.parse(await fs.readFile(projectFile,'utf8'));assert.equal(saved.documents.length,2);assert.equal(saved.documents[1].states.length,2);assert.equal(saved.documents[1].cursor,0);
    assert.equal(saved.documents[1].states[0].netLayout.components.length,2);assert.equal(saved.documents[1].states[0].netHistory.cursor,3);
    // Publish a second complete save explicitly: a fresh profile has no prior file to back up.
    await page.evaluate(snapshot=>window.polytope.save(snapshot),saved);
    assert.deepEqual(JSON.parse(await fs.readFile(projectFile+'.bak','utf8')),saved);
    await page.locator('#new').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Tesseract');
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},projectFile);
    await page.locator('#open').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Cube');
    await page.waitForFunction(()=>document.getElementById('net-summary').textContent.includes('2 connected pieces'));
    await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},offFile);
    await page.locator('#export').click();await page.locator('#export-format').selectOption('off');await page.locator('#confirm-export').click();
    await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Exported '));assert.ok((await fs.readFile(offFile,'utf8')).startsWith('OFF\n8 6 12'));
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},offFile);
    await page.locator('#open').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='smoke');
    const security=await page.evaluate(async()=>{try{await window.polytope.engine({op:'load',params:{path:'C:/Windows/win.ini'}});return false;}catch{return true;}});assert.ok(security);
    await page.locator('[data-key="tesseract"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Tesseract');
    await page.locator('#viewport-layout').selectOption('split');
    await page.locator('#derived-mode').selectOption('section');await page.locator('#section-depth').fill('2');await page.locator('#apply-section').click();
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent==='Empty intersection');
    await page.locator('#section-depth').fill('0');await page.locator('#apply-section').click();
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('8 vertices'));
    await page.locator('#promote').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Section of Tesseract');
    assert.equal(await page.locator('.count-block strong').first().innerText(),'8');
    await page.locator('[data-panel="evidence"]').click();await page.locator('#symmetry').click();
    await page.waitForFunction(()=>document.getElementById('symmetry-result').textContent.includes('Order 48'));
    await page.locator('#rational-points').fill('0,0,0\n1/3,0,0\n0,1/2,0\n0,0,1');
    await page.locator('#rational-hull').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Rational convex hull');
    assert.equal(await page.locator('#numeric-badge').innerText(),'RATIONAL');
    await page.locator('#rational-dual').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Exact dual of Rational convex hull');
    await page.locator('[data-panel="construct"]').click();
    await page.locator('#coxeter-family').selectOption('B3');await page.locator('#coxeter-rings').fill('101');await page.locator('#wythoff').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='B3 Wythoff 101');
    assert.equal(await page.locator('.count-block strong').first().innerText(),'24');
    await page.locator('#copy-facets').click();await page.locator('#facet').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Faceting of B3 Wythoff 101');
    await page.waitForFunction(()=>document.getElementById('view-diagnostic').title.includes('Source face surface fill')&&Number(document.getElementById('view-diagnostic').dataset.triangles)>0);
    const cancellation=await page.evaluate(async()=>{
      const id='smoke-cancel-'+crypto.randomUUID();
      const job=window.polytope.engine({op:'generate',params:{kind:'wythoff',family:'H4',rings:[1,1,1,1],max_vertices:20000}},id).then(()=>({cancelled:false}),e=>({cancelled:true,error:e.message}));
      await new Promise(resolve=>setTimeout(resolve,100));const accepted=await window.polytope.cancel(id);return {accepted,...await job};
    });assert.ok(cancellation.accepted&&cancellation.cancelled);
    await page.evaluate(savedProject=>window.polytope.autosave(savedProject),saved);
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>!w.isDestroyed()).webContents.send('menu-action','recover'));
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Cube');
    assert.equal(await page.locator('#document-tabs button').count(),2);
    assert.ok(await fs.readFile(projectFile+'.bak','utf8'));
    await page.locator('[data-key="octahedron"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Octahedron');
    await page.locator('[data-panel="construct"]').click();await page.locator('#stellation-evaluate').click();
    await page.waitForFunction(()=>document.getElementById('stellation-summary').textContent.includes('59 observed regions'));
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('1 regions'));
    assert.equal(await page.locator('#stellation-regions input:not(:disabled)').count(),9);
    await page.locator('#stellation-all-bounded').click();
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('9 regions · volume 4'));
    await page.screenshot({path:path.join(artifacts,'workspace-stellation-solid.png')});
    await page.locator('#stellation-enumerate').click();
    await page.waitForFunction(()=>document.getElementById('stellation-search-status').textContent.includes('2 candidates · 4/4 subsets'));
    await page.locator('#stellation-candidate').selectOption('1');await page.locator('#stellation-use-candidate').click();
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('9 regions · volume 4'));
    await page.locator('#stellation-display').selectOption('diagram');
    await page.waitForFunction(()=>document.querySelector('#net-preview svg polygon[data-regions]'));
    await page.screenshot({path:path.join(artifacts,'workspace-stellation-diagram.png')});
    await page.locator('#promote').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Stellation region union of Octahedron');
    assert.equal(await page.locator('.count-block strong').first().innerText(),'14');
    await page.locator('#viewport-layout').selectOption('split');
    await page.locator('#section-depth').fill('0.5');await page.locator('#apply-section').click();
    // Both old and new sections are 2D. Wait for the atomic numeric edit and
    // its native section to finish before promoting the requested offset.
    await page.waitForFunction(()=>{
      const slider=document.getElementById('section-offset'),expected=slider.cloneNode(false);
      // HTML range values snap to their source-dependent step. The saved
      // model below independently proves the exact requested native offset.
      expected.value='0.5';
      return slider.value===expected.value&&document.getElementById('cancel').hidden&&
        !document.getElementById('promote').disabled&&
        document.getElementById('derived-status').textContent.includes('intrinsic 2D');
    });
    await page.locator('#promote').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Section of Stellation region union of Octahedron');
    await page.waitForFunction(()=>document.getElementById('analysis').textContent.includes('2.5'));
    const sectionProject=path.join(artifacts,'smoke-union-section.polyproj');
    await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},sectionProject);
    await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Saved '));
    const sectionSaved=JSON.parse(await fs.readFile(sectionProject,'utf8'));
    const sectionModel=sectionSaved.documents[sectionSaved.active].states[0].model;
    assert.equal(sectionModel.metadata.sectionEmbedding.offset,0.5);
    assert.deepEqual(sectionModel.metadata.sectionEmbedding.normal,[0,0,1]);
    const sectionAnalysis=await page.evaluate(model=>window.polytope.engine({op:'analyze',model}),sectionModel);
    assert.ok(Math.abs(sectionAnalysis.measure.content-2.5)<1e-8);
    await page.locator('[data-key="icosahedron"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Icosahedron');
    await page.locator('[data-panel="evidence"]').click();await page.locator('#symmetry').click();
    await page.waitForFunction(()=>document.getElementById('symmetry-result').textContent.includes('Order 120'));
    await page.locator('[data-panel="construct"]').click();await page.locator('#stellation-evaluate').click();
    await page.waitForFunction(()=>document.getElementById('stellation-summary').textContent.includes('703 observed regions'),null,{timeout:40000});
    assert.equal(await page.locator('#stellation-regions input:not(:disabled)').count(),341);
    await page.locator('#stellation-enumerate').click();
    await page.waitForFunction(()=>document.getElementById('stellation-search-status').textContent.includes('13 candidates · 256/256 subsets'),null,{timeout:40000});
    assert.ok((await page.locator('#stellation-search-status').innerText()).includes('order 120 (full numerical source group)'));
    await page.screenshot({path:path.join(artifacts,'workspace-icosahedral-stellation.png')});
    await page.locator('[data-key="dodecahedron"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Dodecahedron');
    await page.locator('[data-panel="net"]').click();await page.locator('#net-length').fill('65');await page.locator('#net-separate').click();
    await page.waitForFunction(()=>document.getElementById('net-summary').textContent.includes('12 connected pieces'));
    await page.locator('#net-pack').click();await page.waitForFunction(()=>document.getElementById('net-paper-status').textContent.includes('Page 1 of 6'));
    assert.ok((await page.locator('#net-paper-status').innerText()).includes('E0 = 65 mm · 100% source scale'));
    await page.locator('#net-page-next').click();await page.waitForFunction(()=>document.getElementById('net-paper-status').textContent.includes('Page 2 of 6'));
    await page.screenshot({path:path.join(artifacts,'workspace-packed-net-pages.png')});
    const packedFile=path.join(artifacts,'smoke-packed.pdf');
    await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},packedFile);
    await page.locator('#net-packed-pdf').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Exported packed net PDF'));
    assert.ok((await fs.readFile(packedFile)).subarray(0,4).toString()==='%PDF');
    const packedProject=path.join(artifacts,'smoke-packed.polyproj');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},packedProject);
    await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Saved '));
    const packedSaved=JSON.parse(await fs.readFile(packedProject,'utf8'));assert.equal(packedSaved.documents[packedSaved.active].states[0].netPages.pageCount,6);
    await page.locator('[data-key="tesseract"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Tesseract');
    await page.locator('#cell-net-build').click();await page.waitForFunction(()=>document.getElementById('cell-net-summary').textContent.includes('8 complete cells · 1 connected pieces'));
    const face=await page.evaluate(async()=>{const model=await window.polytope.engine({op:'generate',params:{kind:'regular',key:'tesseract'}});const net=await window.polytope.engine({op:'cell-net',model});return net.connections[0];});
    await page.locator('#cell-net-face').fill(String(face));await page.locator('#cell-net-match').click();
    assert.ok((await page.locator('#cell-net-selection').innerText()).includes('Matching cells:'));
    await page.locator('#cell-net-toggle').click();await page.waitForFunction(()=>document.getElementById('cell-net-summary').textContent.includes('2 connected pieces'));
    const component=await page.locator('#cell-net-component option').nth(1).getAttribute('value');await page.locator('#cell-net-component').selectOption(component);
    await page.locator('#cell-net-translation').fill('2, 3, 4');await page.locator('#cell-net-angles').fill('20, 30, 40');await page.locator('#cell-net-move').click();
    await page.waitForFunction(()=>document.getElementById('cell-net-summary').dataset.edit==='2');
    await page.locator('#cell-net-undo').click();await page.waitForFunction(()=>document.getElementById('cell-net-summary').dataset.edit==='1');
    await page.locator('#cell-net-undo').click();await page.waitForFunction(()=>document.getElementById('cell-net-summary').textContent.includes('1 connected pieces'));
    await page.locator('#cell-net-redo').click();await page.waitForFunction(()=>document.getElementById('cell-net-summary').textContent.includes('2 connected pieces'));
    await page.locator('#cell-net-redo').click();await page.waitForFunction(()=>document.getElementById('cell-net-summary').dataset.edit==='2');
    await page.locator('#cell-net-shrink').evaluate(p=>{p.value='0.6';p.dispatchEvent(new Event('input',{bubbles:true}));});
    await page.waitForFunction(()=>document.getElementById('cell-net-shrink-value').textContent==='60%');
    await page.screenshot({path:path.join(artifacts,'workspace-tesseract-cell-net.png')});
    const cellProject=path.join(artifacts,'smoke-cell-net.polyproj');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},cellProject);
    await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Saved '));
    const cellSaved=JSON.parse(await fs.readFile(cellProject,'utf8'));assert.equal(cellSaved.documents[cellSaved.active].states[0].cellNetLayout.cells.length,8);assert.equal(cellSaved.documents[cellSaved.active].states[0].cellNetLayout.components.length,2);
    await page.locator('#new').click();await page.waitForFunction(count=>document.getElementById('document-tabs').children.length===count,cellSaved.documents.length+1);
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},cellProject);
    await page.locator('#open').click();await page.waitForFunction(count=>document.getElementById('document-tabs').children.length===count,cellSaved.documents.length);
    await page.waitForFunction(()=>document.getElementById('cell-net-summary').textContent.includes('8 complete cells · 2 connected pieces'));
    await page.locator('#search').fill('snub cube');await page.locator('[data-key="snub-cube"]').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Snub cube (A)');
    assert.equal(await page.locator('.count-block strong').first().innerText(),'24');
    await page.locator('[data-panel="evidence"]').click();await page.locator('#symmetry').click();
    await page.waitForFunction(()=>document.getElementById('symmetry-result').textContent.includes('Order 24; proper order 24'));
    await page.screenshot({path:path.join(artifacts,'workspace-snub-cube.png')});
    await page.locator('[data-key="snub-cube-mirror"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Snub cube (B)');
    await page.locator('[data-panel="info"]').click();await page.waitForFunction(()=>document.getElementById('analysis').textContent.includes('Enantiomorph (coordinate convention)B'));
    await page.locator('#search').fill('hexacontahedron');await page.locator('[data-key="pentagonal-hexecontahedron"]').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Pentagonal hexecontahedron (A)');
    assert.equal(await page.locator('.count-block strong').first().innerText(),'92');
    await page.screenshot({path:path.join(artifacts,'workspace-catalan-dual.png')});
    await page.locator('#search').fill('');await page.locator('[data-key="small-stellated-dodecahedron"]').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Small stellated dodecahedron');
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('12 vertices'));
    assert.equal(await page.locator('#derived-mode').inputValue(),'incidence-dual');
    await page.waitForFunction(()=>document.getElementById('analysis').textContent.includes('Surface genus4'));
    assert.match(await page.locator('#view-diagnostic').getAttribute('title'),/Source face surface fill.*no solid interior/);
    assert.ok(Number(await page.locator('#view-diagnostic').getAttribute('data-triangles'))>0);
    assert.equal(await page.locator('#selection-kind').inputValue(),'vertex');assert.ok((await page.locator('#selection-info').innerText()).includes('select a source entity'));
    await page.locator('#selection-kind').selectOption('face');await page.locator('#selection-id').fill('2');await page.locator('#select-entity').click();
    await page.screenshot({path:path.join(artifacts,'workspace-kepler-poinsot.png')});
    const starOff=path.join(artifacts,'smoke-star.off');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},starOff);
    await page.locator('#export').click();await page.locator('#export-format').selectOption('off');await page.locator('#confirm-export').click();
    await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Exported '));assert.ok((await fs.readFile(starOff,'utf8')).startsWith('OFF'));
    await page.locator('[data-panel="construct"]').click();await page.locator('#make-incidence-dual').click();
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Incidence dual of Small stellated dodecahedron');
    assert.equal(await page.locator('.count-block strong').first().innerText(),'12');
    await page.locator('#undo').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Small stellated dodecahedron');
    await page.locator('#redo').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Incidence dual of Small stellated dodecahedron');
    const starProject=path.join(artifacts,'smoke-star.polyproj');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},starProject);
    await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Saved '));
    const starSaved=JSON.parse(await fs.readFile(starProject,'utf8')),starDoc=starSaved.documents[starSaved.active];
    assert.equal(starDoc.states[0].model.metadata.facePolygon.step,2);assert.equal(starDoc.states[0].model.validation.eulerCharacteristic,-6);assert.equal(starDoc.states[1].model.provenance.operation,'incidence-dual');
    await page.locator('#new').click();await page.waitForFunction(count=>document.getElementById('document-tabs').children.length===count,starSaved.documents.length+1);
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},starProject);
    await page.locator('#open').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Incidence dual of Small stellated dodecahedron');
    await page.locator('#undo').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Small stellated dodecahedron');assert.equal(await page.locator('#selection-kind').inputValue(),'face');assert.equal(await page.locator('#selection-id').inputValue(),'2');
    await page.locator('#redo').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Incidence dual of Small stellated dodecahedron');
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},starOff);
    await page.locator('#open').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='smoke-star');
    await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('intrinsic 2D'));
    assert.equal(await page.locator('#derived-mode').inputValue(),'face');
    await page.locator('[data-panel="info"]').click();await page.waitForFunction(()=>document.getElementById('analysis').textContent.includes('generalized-complex'));
    assert.equal(await page.locator('.count-block strong').first().innerText(),'12');
    await page.locator('[data-key="cube"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Cube');
    await page.locator('#measure-a-kind').selectOption('face');await page.locator('#measure-a-ids').fill('0');await page.locator('#measure-b-kind').selectOption('face');await page.locator('#measure-b-ids').fill('5');
    await page.locator('#measure-flat-distance').click();await page.waitForFunction(()=>document.getElementById('entity-measure-result').textContent.startsWith('2 model-units'));
    assert.ok((await page.locator('#entity-measure-result').innerText()).includes('infinite supporting affine flats'));
    await page.locator('#measure-flat-angle').click();await page.waitForFunction(()=>document.getElementById('entity-measure-result').textContent.includes('principal angles'));
    await page.locator('#measure-entity-info').click();await page.waitForFunction(()=>document.getElementById('entity-measure-result').textContent.startsWith('Content: 4 model-units^2'));
    assert.ok((await page.locator('#entity-measure-result').innerText()).includes('Circumradius: 1.4142136'));
    await page.locator('#measure-dihedral').click();await page.waitForFunction(()=>document.getElementById('entity-measure-result').textContent.startsWith('90 degrees'));
    await page.locator('#measure-a-kind').selectOption('vertex');await page.locator('#measure-a-ids').fill('7');await page.locator('#measure-b-kind').selectOption('edge');await page.locator('#measure-b-ids').fill('0');await page.locator('#measure-bounded').check();
    await page.locator('#measure-flat-distance').click();await page.waitForFunction(()=>document.getElementById('entity-measure-result').textContent.includes('bounded source vertices/edge segments'));
    assert.ok((await page.locator('#entity-measure-result').innerText()).startsWith('2.8284271 model-units'));
    await page.locator('[data-key="tesseract"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Tesseract');
    await page.locator('#measure-a-kind').selectOption('cell');await page.locator('#measure-a-ids').fill('0');await page.locator('#measure-b-kind').selectOption('cell');await page.locator('#measure-b-ids').fill('7');await page.locator('#measure-bounded').uncheck();
    await page.locator('#measure-flat-distance').click();await page.waitForFunction(()=>document.getElementById('entity-measure-result').textContent.startsWith('2 model-units'));
    await page.locator('#measure-entity-info').click();await page.waitForFunction(()=>document.getElementById('entity-measure-result').textContent.startsWith('Content: 8 model-units^3'));
    await page.locator('#measure-align-section').click();await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('8 vertices'));
    await page.waitForFunction(()=>document.getElementById('entity-measure-result').dataset.operation==='align-section');
    assert.equal(await page.locator('#derived-mode').inputValue(),'section');
    await page.locator('#measure-align-offset').fill('-0.5');await page.locator('#measure-align-section').click();
    await page.waitForFunction(()=>document.getElementById('section-depth').value==='0.5');await page.waitForFunction(()=>document.getElementById('derived-status').textContent.includes('8 vertices'));
    await page.screenshot({path:path.join(artifacts,'workspace-intrinsic-measurements.png')});
    const measuredProject=path.join(artifacts,'smoke-measured.polyproj');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},measuredProject);
    await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Saved '));
    const measuredSaved=JSON.parse(await fs.readFile(measuredProject,'utf8'));measuredSaved.documents[measuredSaved.active].states[0].model.measure.content=123456;
    await fs.writeFile(measuredProject,JSON.stringify(measuredSaved));
    await page.locator('#new').click();await page.waitForFunction(count=>document.getElementById('document-tabs').children.length===count,measuredSaved.documents.length+1);
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},measuredProject);await page.locator('#open').click();
    await page.waitForFunction(count=>document.getElementById('document-tabs').children.length===count,measuredSaved.documents.length);
    await page.waitForFunction(()=>document.getElementById('measure-a-kind').value==='cell');assert.equal(await page.locator('#measure-align-offset').inputValue(),'-0.5');
    await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Saved '));
    const measuredRestored=JSON.parse(await fs.readFile(measuredProject,'utf8'));assert.ok(Math.abs(measuredRestored.documents[measuredRestored.active].states[0].model.measure.content-16)<1e-8);
    await page.locator('[data-key="cell24"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='24-cell');
    await page.locator('[data-panel="evidence"]').click();await page.locator('#symmetry').click();
    await page.waitForFunction(()=>document.getElementById('symmetry-result').dataset.order==='1152');
    assert.ok((await page.locator('#symmetry-result').innerText()).includes('Closure: verified'));
    await page.locator('#symmetry-orbit-kind').selectOption('cell');await page.locator('#symmetry-orbit-id').fill('0');await page.locator('#symmetry-highlight-orbit').click();
    await page.waitForFunction(()=>document.getElementById('symmetry-orbit-result').dataset.size==='24');
    assert.ok((await page.locator('#symmetry-orbit-result').innerText()).includes('stabilizer order 48'));
    await page.locator('#symmetry-inspect-action').click();assert.ok((await page.locator('#symmetry-action-result').innerText()).includes('Vertex permutation (source → image)'));
    const reflectionId=await page.evaluate(async()=>{const model=await window.polytope.engine({op:'generate',params:{kind:'regular',key:'cell24'}}),group=await window.polytope.engine({op:'symmetry',model});return group.actions.findIndex(a=>a.matrix.every((row,i)=>row.every((x,j)=>Math.abs(x-(i===j?(i===0?-1:1):0))<1e-8)));});
    assert.ok(reflectionId>=0);await page.locator('#symmetry-generator-ids').fill(String(reflectionId));await page.locator('#symmetry').click();await page.waitForFunction(()=>document.getElementById('symmetry-result').dataset.order==='2');
    assert.ok((await page.locator('#symmetry-result').innerText()).includes('proper order 1'));await page.locator('#symmetry-generator-ids').fill('');
    await page.locator('#symmetry-orientation').selectOption('proper');await page.locator('#symmetry').click();await page.waitForFunction(()=>document.getElementById('symmetry-result').dataset.order==='576');
    await page.locator('#symmetry-stabilize').selectOption('vertex');await page.locator('#symmetry-stabilize-id').fill('0');await page.locator('#symmetry').click();
    await page.waitForFunction(()=>document.getElementById('symmetry-result').dataset.order==='24');assert.ok((await page.locator('#symmetry-result').innerText()).includes('exhaustive selected subgroup'));
    await page.locator('#symmetry-generator-ids').fill('identity');await page.locator('#symmetry').click();await page.waitForFunction(()=>document.getElementById('symmetry-result').dataset.order==='1');
    const symmetryProject=path.join(artifacts,'smoke-symmetry.polyproj');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},symmetryProject);
    await page.locator('#save').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Saved '));
    const symmetrySaved=JSON.parse(await fs.readFile(symmetryProject,'utf8'));assert.equal(symmetrySaved.documents[symmetrySaved.active].states[0].view.symmetry.orientation,'proper');
    await page.locator('#new').click();await page.waitForFunction(count=>document.getElementById('document-tabs').children.length===count,symmetrySaved.documents.length+1);
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},symmetryProject);await page.locator('#open').click();
    await page.waitForFunction(count=>document.getElementById('document-tabs').children.length===count,symmetrySaved.documents.length);
    assert.equal(await page.locator('#symmetry-orientation').inputValue(),'proper');assert.equal(await page.locator('#symmetry-stabilize').inputValue(),'vertex');assert.equal(await page.locator('#symmetry-generator-ids').inputValue(),'identity');
    await page.locator('#symmetry-method').selectOption('signed-axis');await page.locator('#symmetry').click();await page.waitForFunction(()=>document.getElementById('symmetry-result').dataset.order==='384');
    assert.ok((await page.locator('#symmetry-result').innerText()).includes('verified signed-coordinate subgroup'));
    await page.locator('[data-key="cell600"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='600-cell');await page.locator('#symmetry').click();
    await page.waitForFunction(()=>document.getElementById('symmetry-result').dataset.order==='14400',null,{timeout:45000});
    await page.locator('#symmetry-orbit-kind').selectOption('vertex');await page.locator('#symmetry-highlight-orbit').click();await page.waitForFunction(()=>document.getElementById('symmetry-orbit-result').dataset.size==='120');
    await page.screenshot({path:path.join(artifacts,'workspace-4d-symmetry.png')});
    // A large source job may finish after a document switch; it must not replace new-source evidence.
    await page.locator('#symmetry').click();await page.locator('#new').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Tesseract');
    await page.waitForFunction(()=>document.getElementById('cancel').hidden,null,{timeout:45000});
    assert.equal(await page.locator('#symmetry-result').getAttribute('data-order'),null);
    await page.locator('[data-key="octahedron"]').click();await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Octahedron');await page.locator('[data-panel="construct"]').click();
    await page.locator('#stellation-evaluate').click();await page.waitForFunction(()=>document.getElementById('stellation-summary').textContent.includes('59 observed regions'));
    await page.locator('#stellation-symmetry').selectOption('geometric-proper');await page.locator('#stellation-enumerate').click();await page.waitForFunction(()=>document.getElementById('stellation-search-status').textContent.includes('acting group order 24'));
    assert.ok((await page.locator('#stellation-search-status').innerText()).includes('(selected subgroup)'));
    const reflection3=await page.evaluate(async()=>{const model=await window.polytope.engine({op:'generate',params:{kind:'regular',key:'octahedron'}}),group=await window.polytope.engine({op:'symmetry',model});return group.actions.findIndex(a=>a.matrix.every((row,i)=>row.every((x,j)=>Math.abs(x-(i===j?(i===0?-1:1):0))<1e-8)));});
    await page.locator('#stellation-symmetry').selectOption('geometric');await page.locator('#stellation-generator-ids').fill(String(reflection3));await page.locator('#stellation-enumerate').click();await page.waitForFunction(()=>document.getElementById('stellation-search-status').textContent.includes('acting group order 2 (selected subgroup)'));
    assert.equal(await page.locator('#stellation-candidate option').count(),16);
    assert.deepEqual(errors,[]);
    await fs.writeFile(path.join(artifacts,packaged?'packaged-smoke.json':'desktop-smoke.json'),JSON.stringify({passed:true,version:await app.evaluate(({app})=>app.getVersion()),rendererUrl:page.url(),packaged:Boolean(packaged),checks:['launch','GPU views','linked sections','dual','undo/redo','rectification','expressions','measurements','net','native project save/load','OFF export/import','IPC restrictions','empty section','promote','symmetry','net PDF','exact rational hull','exact rational dual','Wythoff','manual faceting','job cancellation','autosave recovery','prior save backup','plane arrangement','bounded region selection','stellation diagram','stellation solid promotion','nonconvex union section','finite orbit-union enumeration','full geometric symmetry','icosahedral stellation search','net hinge editing','net placement and dragging','net edit undo/redo','rigid fold preview and playback','net layout persistence','whole-cell 4D nets','matching source faces','cell-net cuts and placements','cell-net history and persistence','display-only cell shrink','standard-page packing preview','multi-page net PDF','uniform chiral references','snub mirror selection','Catalan alias search','regular star incidence','incidence dual undo/redo','star native persistence','star OFF boundary roundtrip','source selection persistence','intrinsic affine-flat distance','bounded segment distance','principal direction angles','entity area-volume-circumradius','convex interior dihedrals','entity-aligned sections','measurement settings and cache revalidation','full 4D geometric groups','proper rotational subgroup','setwise source entity stabilizer','symmetry entity orbits and highlighting','symmetry action and generators','explicit signed-axis comparison','symmetry settings persistence','stale symmetry response rejection','generator-defined source subgroup','subgroup-constrained region search'],pageErrors:errors},null,2));
    console.log('Desktop smoke passed: 68 workflow checks, no renderer errors.');
  }catch(e){console.error('Smoke failed:',e);console.log(await page.locator('body').innerText().catch(()=>'<no document>'));
    console.log('Section readiness:',await page.evaluate(()=>({
      depth:document.getElementById('section-depth')?.value,slider:document.getElementById('section-offset')?.value,
      step:document.getElementById('section-offset')?.step,derived:document.getElementById('derived-status')?.textContent,
      running:!document.getElementById('cancel')?.hidden,promoteDisabled:document.getElementById('promote')?.disabled,
    })).catch(()=>null));throw e;}
  finally{await app.evaluate(({app})=>app.exit(0)).catch(()=>{});}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
