const {_electron:electron}=require('playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),THREE=require('three');
const root=path.resolve(__dirname,'..'),active=project=>{const d=project.documents[project.active];return d.states[d.cursor];};
const geometry=model=>Object.fromEntries(['dimension','embeddingDimension','vertices','edges','faces','cells'].map(k=>[k,model[k]]));
const literal=()=>({name:'Independent near-clipped perspective fixture',dimension:4,embeddingDimension:4,interpretation:'generalized-complex',vertices:[[1,0,0,0],[-1,0,0,0],[0,1,0,0],[0,-1,0,0],[0,0,1,0],[0,0,-1,0],[0,0,0,1],[0,0,0,-1]],edges:[[0,2],[2,6],[6,0]],faces:[[0,2,6]],cells:[]});
async function main(){
  const artifacts=path.resolve(process.env.POLYTOPE_TEST_ARTIFACTS||path.join(root,'artifacts'));await fs.mkdir(artifacts,{recursive:true});
  const packaged=process.env.POLYTOPE_TEST_EXECUTABLE,folder=await fs.mkdtemp(path.join(artifacts,packaged?'perspective4d-packaged-':'perspective4d-smoke-')),profile=path.join(folder,'profile');await fs.mkdir(profile);await fs.writeFile(path.join(profile,'linked-libraries.json'),JSON.stringify({version:1,paths:[]}));
  const env={...process.env,POLYTOPE_TEST_USER_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;if(packaged)env.POLYTOPE_PYTHON=path.join(folder,'unavailable-python.exe');
  const app=await electron.launch({executablePath:packaged||require('electron'),args:packaged?[]:[root],cwd:root,env,timeout:30000}),page=await app.firstWindow();page.setDefaultTimeout(30000);const checks=[],errors=[],evidence=[];let sequence=0;
  page.on('pageerror',error=>errors.push(error.message));
  const ready=async()=>{await page.waitForFunction(()=>document.getElementById('cancel').hidden);for(let i=0;i<5;i++)await page.evaluate(()=>new Promise(requestAnimationFrame));};
  async function save(label){await ready();await page.keyboard.press('Escape');const file=path.join(folder,`${++sequence}-${label}.polyproj`);await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},file);await page.evaluate(()=>document.getElementById('status').textContent='');await page.locator('#save').click();await page.waitForFunction(file=>document.getElementById('status').textContent==='Saved '+file,file);return {file,project:JSON.parse(await fs.readFile(file,'utf8'))};}
  async function open(file,name){await ready();await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.locator('#open').click();await page.waitForFunction(name=>document.getElementById('model-name').textContent===name,name);await ready();}
  async function create(label,model,view){const file=path.join(folder,label+'.polyproj');await fs.writeFile(file,JSON.stringify({format:'polytope-laboratory',version:1,active:0,documents:[{id:label,cursor:0,states:[{model,view,label,notes:''}]}]}));return file;}
  async function number(id,value){await page.locator('#rotation-settings').evaluate(n=>n.open=true);await page.locator('#'+id).evaluate((n,value)=>{n.value=String(value);n.dispatchEvent(new Event('change',{bubbles:true}));},value);await ready();}
  async function appearance(id,value){await page.locator('#surface-settings').evaluate(n=>n.open=true);const n=page.locator('#'+id);if(await n.evaluate(n=>n.tagName==='SELECT'))await n.selectOption(value);else await n.evaluate((n,value)=>{n.value=String(value);n.dispatchEvent(new Event('input',{bubbles:true}));},value);await ready();}
  async function positions(points){const v=active((await save('camera')).project).view.camera,box=await page.locator('#base-canvas canvas').boundingBox(),half=v.orthographicHalfHeight;const c=new THREE.OrthographicCamera(-half*box.width/box.height,half*box.width/box.height,half,-half,.01,10000000);c.position.fromArray(v.position);c.up.fromArray(v.up);c.zoom=v.zoom;c.lookAt(new THREE.Vector3(...v.target));c.updateProjectionMatrix();c.updateMatrixWorld();return points.map(p=>{const q=new THREE.Vector3(...p).project(c);return [box.x+(q.x+1)*box.width/2,box.y+(1-q.y)*box.height/2];});}
  async function pick(point,kind,id){await page.keyboard.press('Escape');await page.locator('#pick-kind').selectOption(kind);await ready();const [pixel]=await positions([point]);await page.mouse.click(...pixel);await ready();const selected=JSON.parse(await page.locator('#selection-info').textContent());assert.equal(selected.kind,kind);assert.equal(selected.index,id);evidence.push({kind,id,point,pixel});}
  async function lightAt(points){const pixels=await positions(points),box=await page.locator('#base-canvas canvas').boundingBox();return page.evaluate(({pixels,box})=>{const source=document.querySelector('#base-canvas canvas'),c=document.createElement('canvas');c.width=source.width;c.height=source.height;const ctx=c.getContext('2d');ctx.drawImage(source,0,0);return pixels.map(([x,y])=>{const ix=Math.round((x-box.x)*source.width/box.width),iy=Math.round((y-box.y)*source.height/box.height);const data=ctx.getImageData(ix-2,iy-2,5,5).data;let peak=0;for(let i=0;i<data.length;i+=4)peak=Math.max(peak,(data[i]+data[i+1]+data[i+2])/3);return peak;});},{pixels,box});}
  try{
    await page.waitForFunction(()=>document.getElementById('model-name').textContent==='Tesseract');await ready();
    await app.evaluate(({ipcMain})=>{globalThis.__perspectiveJobs=0;const old=ipcMain._invokeHandlers.get('engine');ipcMain._invokeHandlers.set('engine',async(event,request,...args)=>{if(request?.op==='cell-facing')globalThis.__perspectiveJobs++;return old(event,request,...args);});});
    await page.evaluate(()=>{const p=WebGL2RenderingContext.prototype;for(const method of ['drawElementsInstanced','drawArraysInstanced']){const old=p[method];p[method]=function(...args){if(this.canvas.closest('#base-canvas'))(globalThis.__perspectiveDraws??=[]).push({instances:args.at(-1)});return old.apply(this,args);};}});
    const initial=active((await save('initial')).project),zero={...initial.view,angles:Array(6).fill(0),orientationFrame:null,projection:'perspective',cameraProjection:'orthographic',faces:true,vertices:false,edges:true,hiddenCells:[],isolatedCell:null,cellFacing:'all',cellFacingCache:null,cellShrink:1,vertexStyle:'point',edgeStyle:'line',surfaceOpacity:.22,perspectiveDistance4D:3,perspectiveNear4D:.08};
    const cube={...initial.model,name:'Independent adjustable tesseract fixture'},file=await create('aligned-tesseract',cube,zero);await open(file,cube.name);await page.locator('#view-orientation').selectOption('z');await page.locator('#fit-view').click();
    assert.equal(await page.locator('#perspective-distance-4d').inputValue(),'3');assert.equal(await page.locator('#perspective-near-4d').inputValue(),'0.08');assert.doesNotMatch(await page.locator('#view-diagnostic').textContent(),/near plane/);
    const defaultLights=await lightAt([[.6,.6,0],[3/7,3/7,0]]);assert.ok(defaultLights.every(x=>x>35));checks.push('legacy default eye3/near.08 renders aligned front/back cube edges at independent coordinates .6 and3/7');
    await number('perspective-distance-4d',.6);await page.keyboard.press('Escape');await page.locator('#fit-view').click();const schlegelLights=await lightAt([[3,3,0],[3/11,3/11,0]]);assert.ok(schlegelLights.every(x=>x>35));evidence.push({defaultLights,schlegelLights,independentFrontBackRatio:11});await page.screenshot({path:path.join(folder,'tesseract-schlegel-distance-.6.png')});
    await appearance('cell-facing','hide-front');await page.waitForFunction(()=>document.getElementById('cell-facing-result').textContent==='1 front / 7 back / 0 grazing');const jobs=await app.evaluate(()=>globalThis.__perspectiveJobs);assert.equal(jobs,1);
    await number('perspective-distance-4d',.4);await page.waitForFunction(()=>document.getElementById('cell-facing-result').textContent==='0 front / 8 back / 0 grazing');assert.match(await page.locator('#view-diagnostic').textContent(),/near plane/);
    await number('perspective-distance-4d',.5);await page.waitForFunction(()=>document.getElementById('cell-facing-result').textContent==='0 front / 7 back / 1 grazing');assert.equal(await app.evaluate(()=>globalThis.__perspectiveJobs),jobs);checks.push('distance.6 gives literal Schlegel size ratio11; observer facing changes at.4/.5/.6 with one source-plane job');
    const model=literal(),cross=await create('source-near-clipping',model,{...zero,perspectiveDistance4D:.6,surfaceOpacity:1,pickKind:'edge'});await open(cross,model.name);await page.locator('#view-orientation').selectOption('z');await page.locator('#fit-view').click();assert.match(await page.locator('#view-diagnostic').textContent(),/near plane/);
    await pick([2,0,0],'edge',2);await pick([1,1,0],'face',0);const lights=await lightAt([[2,0,0],[1,1,0],[0,0,0]]);assert.ok(lights[0]>45&&lights[1]>45&&lights[2]<35,JSON.stringify(lights));evidence.push({clippedPatchLights:lights});await page.screenshot({path:path.join(folder,'finite-near-clipped-edge-and-quad.png')});checks.push('actual clipped edge2 and quadrilateral face0 remain visible/pickable beyond original source points; origin has no false bridge');
    await appearance('vertex-style','sphere');await appearance('edge-style','cylinder');await page.evaluate(()=>globalThis.__perspectiveDraws=[]);await ready();const instances=await page.evaluate(()=>[...new Set(globalThis.__perspectiveDraws.map(d=>d.instances))].sort((a,b)=>a-b));assert.deepEqual(instances,[3,7]);await pick([2,0,0],'edge',2);await page.screenshot({path:path.join(folder,'near-clipped-source-cylinders-and-spheres.png')});checks.push('actual GPU draws keep three retained source cylinders and seven original source spheres; clipped north-pole source point creates no sphere');
    await number('perspective-near-4d',.2);await page.keyboard.press('Escape');await page.locator('#fit-view').click();await pick([1.5,0,0],'edge',2);const before=await page.locator('#selection-info').textContent();const [outside]=await positions([[2,0,0]]);await page.mouse.click(...outside);await ready();assert.equal(await page.locator('#selection-info').textContent(),before);checks.push('near depth.2 moves the actual retained edge endpoint to1.8; former finite endpoint region is no longer pickable');
    const saved=await save('persisted-distance-near-source'),state=active(saved.project);assert.deepEqual(geometry(state.model),geometry(model));assert.equal(state.view.perspectiveDistance4D,.6);assert.equal(state.view.perspectiveNear4D,.2);assert.equal(state.view.edgeStyle,'cylinder');assert.equal(state.view.vertexStyle,'sphere');assert.deepEqual(state.view.entitySelection,{kind:'edge',index:2});
    await number('perspective-distance-4d',3);await open(saved.file,model.name);await page.waitForFunction(()=>document.getElementById('perspective-distance-4d').value==='0.6');assert.equal(await page.locator('#perspective-near-4d').inputValue(),'0.2');await pick([1.5,0,0],'edge',2);assert.deepEqual(geometry(active((await save('reopened-source')).project).model),geometry(model));checks.push('native save/reopen restores distance/near/styles/source selection and camera without changing source coordinates or incidence');
    for(const [field,value] of [['perspectiveDistance4D',0],['perspectiveDistance4D',101],['perspectiveNear4D',.6]]){const bad=structuredClone(saved.project);active(bad).view[field]=value;active(bad).model.name='Invalid perspective settings fixture';const badfile=path.join(folder,field+'-'+value+'.polyproj');await fs.writeFile(badfile,JSON.stringify(bad));await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},badfile);await page.evaluate(()=>document.getElementById('status').textContent='');await page.locator('#open').click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('Saved 4D perspective requires'));await ready();assert.equal(await page.locator('#model-name').textContent(),model.name);}
    checks.push('native project validation rejects eye0/101 and near>=distance before adopting malformed source state');
    assert.deepEqual(errors,[]);await fs.writeFile(path.join(folder,'result.json'),JSON.stringify({passed:true,packaged:Boolean(packaged),version:await app.evaluate(({app})=>app.getVersion()),checks,evidence,pageErrors:errors},null,2));console.log(`Perspective4D desktop smoke passed: ${checks.length} checks. Artifacts: ${folder}`);
  }catch(error){await page.screenshot({path:path.join(folder,'failure.png')}).catch(()=>{});await fs.writeFile(path.join(folder,'failure.json'),JSON.stringify({passed:false,error:error.stack,checks,evidence,pageErrors:errors},null,2));console.error('Artifacts:',folder);console.error(await page.locator('body').innerText().catch(()=>''));throw error;}finally{await app.evaluate(({app})=>app.exit(0)).catch(()=>{});}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
