// Actual strict Waterman controls. No visible launches; root must first qualify
// the selected hidden runtime under its native HWND watcher. --self-test is Node only.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {createHash}=require('node:crypto'),root=path.resolve(__dirname,'..');
const doc=p=>p.documents[p.active],active=p=>doc(p).states[doc(p).cursor];
const geometry=m=>Object.fromEntries(['dimension','embeddingDimension','vertices','edges','faces','cells','fingerprint'].map(k=>[k,m[k]]));
const counts=m=>['vertices','edges','faces','cells'].map(k=>m[k].length),hash=x=>createHash('sha256').update(x).digest('hex');
const near=(a,b)=>assert.ok(Number.isFinite(a)&&Math.abs(a-b)<=1e-10*Math.max(1,Math.abs(b)),`${a} != ${b}`);
const gcd=(a,b)=>{a=a<0n?-a:a;while(b){[a,b]=[b,a%b];}return a;};
function rational(value){const parts=String(value).trim().split('/');assert.ok(parts.length<=2&&parts.every(s=>/^[+-]?\d+$/.test(s)));const n=BigInt(parts[0]),d=BigInt(parts[1]||'1');assert.ok(d>0n);const g=gcd(n,d);return [n/g,d/g];}
const add=(a,b)=>rational(`${a[0]*b[1]+b[0]*a[1]}/${a[1]*b[1]}`),square=a=>[a[0]*a[0],a[1]*a[1]];
const compare=(a,b)=>a[0]*b[1]-b[0]*a[1],literal=a=>a[1]===1n?String(a[0]):a.join('/');
const coordinateKey=p=>p.map(x=>x===0?0:x).join(','); // JSON -0 and0 are the same lattice number.
const coordinates=points=>points.map(coordinateKey).sort();
const faceKey=(m,ids)=>ids.map(i=>coordinateKey(m.vertices[i])).sort().join('|');
function referenceMembership(radius,center){
  const threshold=rational(radius),origin=center.map(rational);assert.ok(compare(threshold,[20n,1n])<=0n&&origin.every(q=>compare(square(q),[1n,1n])<=0n),'Fixed fixture enumeration only supports r²<=20 and |origin axes|<=1');
  const points=[],distances=[],boundary=[];
  // Fixed independent box; not production projection bounds/scaled numerators.
  for(let x=-6;x<=6;x++)for(let y=-6;y<=6;y++)for(let z=-6;z<=6;z++){
    if((x+y+z)%2)continue;const p=[x,y,z];let distance=[0n,1n];for(let i=0;i<3;i++)distance=add(distance,square([BigInt(p[i])*origin[i][1]-origin[i][0],origin[i][1]]));
    const delta=compare(distance,threshold);if(delta<=0n){if(delta===0n)boundary.push(points.length);points.push(p);distances.push(literal(distance));}
  }
  return {points,distances,boundary,threshold:literal(threshold),center:origin.map(literal)};
}
function verifySelection(m,radius,center){
  const expected=referenceMembership(radius,center),info=m.metadata.watermanFcc,source=info.sourceSnapshot,certificate=info.selectionCertificate;
  assert.equal(m.dimension,3);assert.equal(m.interpretation,'convex-polytope');assert.equal(m.numeric.certified,false);assert.equal(certificate.certified,true);assert.equal(certificate.exhausted,true);
  assert.deepEqual(source.coordinates,expected.points);assert.equal(source.radiusSquared,expected.threshold);assert.deepEqual(source.center,expected.center);assert.equal(info.selectedPointCount,expected.points.length);
  assert.deepEqual(certificate.selectedSquaredDistances,expected.distances);assert.deepEqual(certificate.boundarySelectedPointIds,expected.boundary);
  assert.deepEqual(info.outputVertexToSelectedPoint.map(i=>source.coordinates[i]),m.vertices);assert.equal(new Set(info.outputVertexToSelectedPoint).size,m.vertices.length);
  assert.equal(info.selectedPointToOutputVertex.length,source.coordinates.length);
  info.selectedPointToOutputVertex.forEach((v,i)=>{if(v!==null)assert.equal(info.outputVertexToSelectedPoint[v],i);});assert.deepEqual(info.nonextremeSelectedPointIds,info.selectedPointToOutputVertex.flatMap((v,i)=>v===null?[i]:[]));
  assert.deepEqual(info.faceSelectedPointCycles,m.faces.map(c=>c.map(v=>info.outputVertexToSelectedPoint[v])));assert.deepEqual(info.facetSelectedPointIds,m.facetVertices.map(c=>c.map(v=>info.outputVertexToSelectedPoint[v])));
  assert.equal(info.sourceModelId,m.id);assert.equal(info.sourceFingerprint,m.fingerprint);assert.equal(m.vertices.length-m.edges.length+m.faces.length,2);
  const ordered=Object.fromEntries(Object.keys(source).sort().map(k=>[k,source[k]]));assert.equal(info.sourceSnapshotSha256,hash(JSON.stringify(ordered)));assert.ok(m.measure.content>0);
}
const FIXTURES={
  tetra:{radius:'3/4',center:['1/2','1/2','1/2'],vertices:[[0,0,0],[0,1,1],[1,0,1],[1,1,0]],counts:[4,6,4,0],volume:1/3},
  octa:{radius:'1',center:['1','0','0'],vertices:[[0,0,0],[2,0,0],[1,-1,0],[1,1,0],[1,0,-1],[1,0,1]],counts:[6,12,8,0],volume:4/3},
  pyramid:{radius:'5/4',center:['0','0','1/2'],vertices:[[0,0,0],[-1,0,1],[0,-1,1],[1,0,1],[0,1,1]],counts:[5,8,5,0],volume:2/3}
};
function verifyFixture(m,key){
  const f=FIXTURES[key];verifySelection(m,f.radius,f.center);assert.deepEqual(coordinates(m.vertices),coordinates(f.vertices));assert.deepEqual(counts(m),f.counts);near(m.measure.content,f.volume);
  let expectedFaces,expectedEdges;
  if(key==='tetra'){
    expectedFaces=f.vertices.map((_,omit)=>f.vertices.filter((_,i)=>i!==omit));expectedEdges=f.vertices.flatMap((a,i)=>f.vertices.slice(i+1).map(b=>[a,b]));
  }else if(key==='octa'){
    const pairs=[[f.vertices[0],f.vertices[1]],[f.vertices[2],f.vertices[3]],[f.vertices[4],f.vertices[5]]];expectedFaces=pairs[0].flatMap(a=>pairs[1].flatMap(b=>pairs[2].map(c=>[a,b,c])));expectedEdges=f.vertices.flatMap((a,i)=>f.vertices.slice(i+1).filter(b=>a.reduce((s,x,k)=>s+(x-b[k])**2,0)===2).map(b=>[a,b]));
  }else{
    const [apex,...base]=f.vertices;expectedFaces=[base,...base.map((a,i)=>[apex,a,base[(i+1)%4]])];expectedEdges=[...base.map((a,i)=>[a,base[(i+1)%4]]),...base.map(a=>[apex,a])];
  }
  const keyOf=points=>points.map(coordinateKey).sort().join('|');assert.deepEqual(m.faces.map(ids=>faceKey(m,ids)).sort(),expectedFaces.map(keyOf).sort());assert.deepEqual(m.edges.map(ids=>faceKey(m,ids)).sort(),expectedEdges.map(keyOf).sort());
}

async function main(){
  const runtime=await require('./layer-join-smoke.cjs').guardRuntime();
  const packaged=process.env.POLYTOPE_TEST_EXECUTABLE,entry=packaged?require('@electron/asar').extractFile(path.join(path.dirname(packaged),'resources','app.asar'),'desktop/main.cjs'):await fs.readFile(path.join(root,'desktop','main.cjs'));
  const {_electron:electron}=require('playwright'),started=performance.now(),artifacts=path.resolve(process.env.POLYTOPE_TEST_ARTIFACTS||path.join(root,'artifacts'));await fs.mkdir(artifacts,{recursive:true});const folder=await fs.mkdtemp(path.join(artifacts,packaged?'waterman-packaged-smoke-':'waterman-smoke-')),profile=path.join(folder,'profile');await fs.mkdir(profile);await fs.writeFile(path.join(profile,'linked-libraries.json'),JSON.stringify({version:1,paths:[]}));
  const env={...process.env,POLYTOPE_TEST_USER_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;if(packaged)env.POLYTOPE_PYTHON=path.join(folder,'unavailable-development-python.exe');
  const app=await electron.launch({executablePath:packaged||require('electron'),args:packaged?[]:[root],cwd:root,env,timeout:30000});const checks=[],errors=[],snapshots=[],fixtures=[];let page,serial=0;
  try{
    assert.equal((await app.evaluate(({app})=>app.polytopeQualification))?.mode,runtime.hidden?'hidden-no-focus':undefined);page=await app.firstWindow();page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
    await page.waitForFunction(()=>document.getElementById('waterman-settings')&&document.getElementById('model-name').textContent==='Tesseract');
    await page.evaluate(()=>{window.watermanStatus=[];new MutationObserver(()=>window.watermanStatus.push(document.getElementById('status').textContent)).observe(document.getElementById('status'),{childList:true,subtree:true,characterData:true});});
    const done=()=>page.waitForFunction(()=>document.getElementById('cancel').hidden),disclose=async id=>{if(!await page.locator('#'+id).evaluate(n=>n.open))await page.locator('#'+id+' > summary').click();};
    const construct=async()=>{if(await page.locator('#toggle-inspector').getAttribute('aria-pressed')!=='true')await page.locator('#toggle-inspector').click();await page.locator('[data-panel="construct"]').click();await disclose('waterman-settings');};
    const newDoc=async callback=>{const before=await page.locator('#document-tabs > button').count();await callback();await page.waitForFunction(n=>document.getElementById('document-tabs').children.length===n+1,before);await done();};
    const save=async label=>{await done();const file=path.join(folder,`${String(++serial).padStart(2,'0')}-${label}.polyproj`);await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},file);await page.locator('#save').click();const deadline=Date.now()+30000;let bytes;while(Date.now()<deadline){try{bytes=await fs.readFile(file);JSON.parse(bytes);break;}catch(e){if(e.code!=='ENOENT'&&!(e instanceof SyntaxError))throw e;await new Promise(r=>setTimeout(r,25));}}assert.ok(bytes,'Native save must produce a readable project');await done();snapshots.push({file,sha256:hash(bytes)});return {file,project:JSON.parse(bytes)};};
    const open=async file=>{await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.locator('#open').click();await page.waitForFunction(file=>document.getElementById('status').textContent==='Opened '+file||window.watermanStatus.includes('Opened '+file),file);await done();};
    const exact=async(radius,center=['0','0','0'])=>{await construct();await page.locator('#waterman-mode').selectOption('exact-sphere');await page.locator('#waterman-radius-squared').fill(radius);for(let i=0;i<3;i++)await page.locator('#waterman-'+['x','y','z'][i]).fill(center[i]);await newDoc(()=>page.locator('#generate-waterman').click());};
    const author=async rootValue=>{await construct();await page.locator('#waterman-mode').selectOption('author-root');await page.locator('#waterman-root').fill(String(rootValue));assert.equal(await page.locator('#waterman-radius-squared').isEnabled(),false);assert.equal(await page.locator('#waterman-x-row').isVisible(),false);await newDoc(()=>page.locator('#generate-waterman').click());};
    await done();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1484,900));const initial=(await save('initial')).project,small=[];
    for(const [key,f] of Object.entries(FIXTURES)){await exact(f.radius,f.center);const saved=await save(key);verifyFixture(active(saved.project).model,key);assert.deepEqual(active(saved.project).model.provenance.generator,{kind:'waterman-fcc',parameters:{radius_squared:f.radius,center:f.center}});small.push({key,...saved});}
    assert.deepEqual(geometry(small.at(-1).project.documents[0].states[0].model),geometry(initial.documents[0].states[0].model));checks.push('actual offset tetrahedron/octahedron/pyramid retain independently checked lattice vertices, every edge/face, volumes and original-coordinate frame');

    const denominator=10n**40n,below=`${4n*denominator-1n}/${denominator}`;assert.equal(Number(4n*denominator-1n)/Number(denominator),4);
    await exact(below);const under=active((await save('below-shell')).project).model;verifySelection(under,below,['0','0','0']);assert.deepEqual(counts(under),[12,24,14,0]);assert.equal(under.metadata.watermanFcc.selectedPointCount,13);assert.deepEqual(under.metadata.watermanFcc.selectionCertificate.boundarySelectedPointIds,[]);
    await exact('4');const shell=active((await save('exact-shell')).project).model;verifySelection(shell,'4',['0','0','0']);assert.deepEqual(counts(shell),[6,12,8,0]);assert.equal(shell.metadata.watermanFcc.selectedPointCount,19);assert.equal(shell.metadata.watermanFcc.selectionCertificate.boundarySelectedPointIds.length,6);assert.notEqual(shell.fingerprint,under.fingerprint);
    assert.equal(under.provenance.generator.parameters.radius_squared,below);checks.push('actual4−10^-40 and4 select different complete FCC sets and hulls even though the former rounds to4 in float64');

    await author(5);const five=await save('author-root-five');verifySelection(active(five.project).model,'10',['0','0','0']);assert.equal(active(five.project).model.metadata.watermanFcc.authorRoot,5);await exact('10');const tenDirect=active((await save('squared-radius-ten')).project).model;assert.deepEqual(geometry(tenDirect),geometry(active(five.project).model));assert.equal(tenDirect.metadata.watermanFcc.authorRoot,undefined);
    await author(10);const tenRoot=active((await save('author-root-ten')).project).model;verifySelection(tenRoot,'20',['0','0','0']);assert.equal(tenRoot.metadata.watermanFcc.authorRoot,10);assert.notDeepEqual(tenRoot.vertices,tenDirect.vertices);assert.notEqual(tenRoot.fingerprint,tenDirect.fingerprint);checks.push('actual authorroot5 means r²10; authorroot10 means r²20, with literal coordinates and exact selection distinct from direct r²10');

    await exact('+6/8',['2/4','3/6','4/8']);const raw=await save('raw-rationals'),rawModel=active(raw.project).model;verifyFixture(rawModel,'tetra');assert.equal(rawModel.provenance.rawInput.radius_squared.literal,'3/4');assert.deepEqual(rawModel.provenance.rawInput.center.map(x=>x.literal),['1/2','1/2','1/2']);assert.deepEqual(rawModel.provenance.generator.parameters,{radius_squared:'3/4',center:['1/2','1/2','1/2']});assert.equal(await page.locator('#waterman-radius-squared').inputValue(),'+6/8');
    const colored=structuredClone(raw.project),coloredState=active(colored);coloredState.view.coordinateUnit='mm';coloredState.model.metadata.offColors={faces:[{encoding:'byte',values:[7,70,240,128]},{encoding:'unit',values:[.2,.3,.5,.25]},null,null],cells:[]};const inputFile=path.join(folder,'colored-exact-source.polyproj'),inputBytes=Buffer.from(JSON.stringify(colored));await fs.writeFile(inputFile,inputBytes);fixtures.push({file:inputFile,sha256:hash(inputBytes)});await open(inputFile);const persisted=await save('raw-colored-native');await open(persisted.file);const reopened=active((await save('raw-colored-reopened')).project);assert.deepEqual(geometry(reopened.model),geometry(coloredState.model));assert.deepEqual(reopened.model.metadata,coloredState.model.metadata);assert.deepEqual(reopened.model.provenance,coloredState.model.provenance);assert.equal(reopened.view.coordinateUnit,'mm');verifyFixture(reopened.model,'tetra');checks.push('native Save/Open retains reduced exact certificate, canonical native rational literals, all source maps/hash, byte/unit RGBA and units');

    await construct();await page.locator('#model-scale').fill('2');await page.locator('#scale').click();await done();const scaled=await save('waterman-scale-two'),scaledModel=active(scaled.project).model;assert.deepEqual(scaledModel.vertices,reopened.model.vertices.map(p=>p.map(x=>2*x)));assert.deepEqual(scaledModel.metadata.watermanFcc,reopened.model.metadata.watermanFcc);assert.notEqual(scaledModel.fingerprint,reopened.model.fingerprint);assert.equal(doc(scaled.project).operationHistory.nodes.at(-1).op,'transform');
    await disclose('history-settings');await newDoc(()=>page.locator('#history-replay').click());assert.deepEqual(geometry(active((await save('waterman-scale-replay')).project).model),geometry(scaledModel));await disclose('history-settings');await page.locator('#history-branch').click();await page.locator('#history-parameters').fill('{"scale":3}');await newDoc(()=>page.locator('#history-parameters-apply').click());const branched=await save('waterman-scale-branch');assert.deepEqual(active(branched.project).model.vertices,reopened.model.vertices.map(p=>p.map(x=>3*x)));await open(branched.file);assert.deepEqual(doc((await save('waterman-history-reopened')).project).operationHistory,doc(branched.project).operationHistory);checks.push('actual ordinary scale history seeds exact-source snapshot and supports replay/parent-based parameter branch; generated-only membership evidence is retained without claiming scaled membership');

    await exact('4.0');verifySelection(active((await save('exact-decimal-expression')).project).model,'4',['0','0','0']);
    await author('5/1');verifySelection(active((await save('integer-root-expression')).project).model,'10',['0','0','0']);
    await exact('1-1/4',['1/4+1/4','1/2','2/4']);verifyFixture(active((await save('exact-arithmetic-expression')).project).model,'tetra');checks.push('exact decimal/arithmetic rational expressions and integral root expressions resolve before strict native construction without float64 membership loss');
    const before=(await save('before-refusal')).project;
    const refuse=async(mode,radius,center,error)=>{await construct();await page.locator('#waterman-mode').selectOption(mode);if(mode==='author-root')await page.locator('#waterman-root').fill(radius);else{await page.locator('#waterman-radius-squared').fill(radius);for(let i=0;i<3;i++)await page.locator('#waterman-'+['x','y','z'][i]).fill(center[i]);}await page.evaluate(()=>{document.getElementById('toast').hidden=true;});await page.locator('#generate-waterman').click();await page.waitForFunction(text=>!document.getElementById('toast').hidden&&document.getElementById('toast').textContent.includes(text),error);await done();const refused=(await save('refused-'+serial)).project;assert.equal(refused.documents.length,before.documents.length);assert.equal(doc(refused).states.length,doc(before).states.length);assert.deepEqual(doc(refused).operationHistory,doc(before).operationHistory);assert.deepEqual(geometry(active(refused).model),geometry(active(before).model));};
    for(const [mode,radius,center,error] of [['exact-sphere','sqrt(4)',['0','0','0'],'exact rational'],['exact-sphere','unknown(4)',['0','0','0'],'Unknown equation name'],['author-root','5/2',null,'integer domain'],['exact-sphere','1/0',['0','0','0'],'Invalid expression'],['exact-sphere','1'+'0'.repeat(80),['0','0','0'],'256-bit'],['exact-sphere','1000000',['0','0','0'],'inspected-site'],['exact-sphere','2',['1000001','0','0'],'lattice-coordinate']])await refuse(mode,radius,center,error);
    await exact('3/4',['1/2','1/2','1/2']);verifyFixture(active((await save('refusal-recovered')).project).model,'tetra');checks.push('approximate/unknown-function/nonintegral-root/zero-denominator/resource/domain requests refuse atomically; current full geometry/history survives and a valid exact construction recovers');

    await disclose('animation-settings');for(const [id,value] of [['animation-duration','1'],['animation-fps','2']]){await page.locator('#'+id).fill(value);await page.locator('#'+id).dispatchEvent('change');}await page.locator('#animation-rotation').click();const beforeExport=active((await save('before-export')).project);await disclose('animation-settings');await app.evaluate(({dialog})=>{globalThis.watermanHeld=false;dialog.showSaveDialog=()=>new Promise(resolve=>{globalThis.watermanHeld=true;globalThis.watermanRelease=()=>resolve({canceled:true});});});await page.locator('#animation-target').selectOption('base');await page.locator('#animation-png').click();await page.waitForFunction(()=>!document.getElementById('animation-cancel').hidden);await app.evaluate(()=>new Promise((resolve,reject)=>{const until=Date.now()+5000,t=setInterval(()=>{if(globalThis.watermanHeld){clearInterval(t);resolve();}else if(Date.now()>until){clearInterval(t);reject(Error('Export dialog stub not reached.'));}},10);}));for(const id of ['generate-waterman','waterman-mode','waterman-radius-squared','waterman-x','waterman-y','waterman-z'])assert.equal(await page.locator('#'+id).isEnabled(),false);
    await page.locator('#animation-cancel').click();await app.evaluate(()=>globalThis.watermanRelease());await page.waitForFunction(()=>!document.getElementById('animation-png').disabled);await done();const afterExport=active((await save('after-export')).project);assert.deepEqual(geometry(afterExport.model),geometry(beforeExport.model));assert.deepEqual(afterExport.view,beforeExport.view);assert.equal((await fs.readdir(folder)).filter(x=>x.startsWith('.polytope-animation-')).length,0);checks.push('held explicit export disables exact construction; cancellation restores complete view/source and releases controls with no staging output');

    for(const file of [...fixtures,...snapshots])assert.equal(hash(await fs.readFile(file.file)),file.sha256);assert.deepEqual(errors,[]);await page.screenshot({path:path.join(folder,'waterman-workspace.png')});const sourceHashes=[];for(const file of ['scripts/waterman-smoke.cjs','ui/waterman-controls.mjs','engine/waterman.py'])sourceHashes.push({file,sha256:hash(await fs.readFile(path.join(root,file)))});checks.push('source/native snapshots remain byte-identical; no renderer page errors');
    await fs.writeFile(path.join(folder,'result.json'),JSON.stringify({passed:true,packaged:Boolean(packaged),developmentPythonUnavailable:Boolean(packaged),hidden:runtime.hidden,runtime:runtime.runtime,version:await app.evaluate(({app})=>app.getVersion()),runtimeMainSha256:hash(entry),sourceHashes,sourceHashScope:'workspace source files; packaged qualification manifest collected independently by root',checks,pageErrors:errors,fixtures,nativeSnapshots:snapshots,seconds:(performance.now()-started)/1000},null,2));console.log(`Waterman ${packaged?'packaged ':''}smoke passed: ${checks.length} groups. Artifacts: ${folder}`);
  }catch(error){await page?.screenshot({path:path.join(folder,'failure.png')}).catch(()=>{});const diagnostic=await page?.evaluate(()=>({status:document.getElementById('status')?.textContent,toast:document.getElementById('toast')?.textContent,statusTrace:window.watermanStatus})).catch(()=>null);await fs.writeFile(path.join(folder,'failure.json'),JSON.stringify({passed:false,error:error.stack,checks,pageErrors:errors,diagnostic},null,2));console.error('Artifacts:',folder);throw error;}
  finally{await app.evaluate(({app})=>app.exit(0)).catch(()=>{});}
}

function selfTest(){
  for(const key of ['tetra','octa','pyramid']){const f=FIXTURES[key],actual=referenceMembership(f.radius,f.center);assert.deepEqual(coordinates(actual.points),coordinates(f.vertices));assert.equal(actual.boundary.length,key==='pyramid'?4:f.vertices.length);}
  const d=10n**40n;assert.equal(Number(4n*d-1n)/Number(d),4);const below=referenceMembership(`${4n*d-1n}/${d}`,['0','0','0']),shell=referenceMembership('4',['0','0','0']);assert.equal(below.points.length,13);assert.equal(shell.points.length,19);assert.equal(below.boundary.length,0);assert.equal(shell.boundary.length,6);assert.deepEqual(rational('+6/8'),[3n,4n]);assert.throws(()=>referenceMembership('1000000',['0','0','0']));console.log('Waterman headless fixtures PASS: literal offset sites, independent exact Fraction predicates and float-rounding threshold distinction. No app launched.');
}
if(require.main===module){if(process.argv.includes('--self-test'))selfTest();else main().catch(error=>{console.error(error);process.exitCode=1;});}
module.exports={referenceMembership,verifySelection,verifyFixture,FIXTURES};
